### ISSUE TITLE
Calculating all movie-item recco scores for the MF quick-start tutorial

### ISSUE THREAD

**Issue by nialloh23** [tensorflow/recommenders#101]
I’m currently working my way through the quickstart [matrix factorization retrieval tutorial ](https://www.tensorflow.org/recommenders/examples/quickstart).

The example outlines an approach for narrowing down candidates using brute force search. But for the example use case I’m interested in I would like to calculate the scores for the full suite of movie-users pairs at once and store them for serving. To be confident that I’m doing this correctly my goal was to correctly predict the same top 3 recommendations for user 42 as given in the tutorial [b'Rent-a-Kid (1995)' b'House Arrest (1996)' b'Mirage (1995)']

The approach I’m taking (for quality check) is:
```
movie_embeddings = movie_model.layers[1].get_weights()[0]
users_embeddings = user_model.layers[1].get_weights()[0]

scores = tf.linalg.matmul(
   users_embeddings, movie_embeddings, transpose_b=True)
 
top_movie_indices = tf.argsort(scores[42], direction='DESCENDING')[:3]
 
for indice in top_movie_indices:
   indice_value = indice.numpy()
 
   **#option a -> get title from indice & vocabulary lookup **
   movie_title = movie_titles_vocabulary.get_vocabulary()[indice_value]
 
   **#option b -> get title from indice & movies_ids input into embedding layer**
   movie_titles = movie_model.layers[1].get_weights()[0]
   movie_title = movie_titles[indice_value]
```

Neither option above (a) or  (b) gives me results which match for user 42 so I’m a little confused.
Should the top 3 results from both methodologies match? I may be mapping back to the movie titles via the indices incorrectly? Am I missing a bias term in my score calculations/

Apologies for what may be a simple question but it  I hope it might eventually help with documentation efforts down the line.

**Comment by nialloh23** [comment]
On a somewhat related note:  
Is there an intention to ever expose a predict method  that encapsulates what I'm trying to do above. I'm thinking something along the lines of what we currently use in LightFM like:  
```
        recco_scores = self.model.predict(
            user_ids=user_idx,
            item_ids=self.all_style_indexes,
            user_features=self.X_user,
            item_features=self.X_item,
        )
```  
Or has this been left intentionally flexible? It would appear the default approach being suggested is to use query/candidate approach/thinking which relies on search methods like brute/approx annoy versus conventional dot product calculations for the full dataset. Is this because it is envisaged this package will be used with much larger datasets? If the dataset size is smaller or the recco scores can be generated offline does it make more sense to just calculate the dot product of the embedding layers as outlined above?

**Comment by maciejkula** [comment]
> Is this because it is envisaged this package will be used with much larger datasets for candidate shortlisting?

This is exactly right: we expect retrieval models to commonly work with millions of candidates.

Even for precomputing dense user-item scores, I'd still recommend using the `BruteForce` layer (setting `num_candidates` to a large number), as it will correctly take care of the vocabulary translation for you.

Having said that, the approach you outline in your code is almost there, but needs a small fix to get indices from user and movie vocabularies correctly. The following works and reproduces the `BruteForice` layer results:

```python
movie_embeddings = movie_model.layers[1].get_weights()[0]
users_embeddings = user_model.layers[1].get_weights()[0]

scores = tf.linalg.matmul(
   users_embeddings, movie_embeddings, transpose_b=True)
 
# Get the user index.
user_index = user_ids_vocabulary("42")

# Get the scores.
user_scores = scores[user_index]

top_movie_indices = tf.argsort(user_scores, direction='DESCENDING')[:3].numpy()

# Translate back into titles.
index_to_title = tf.keras.layers.experimental.preprocessing.StringLookup(
    vocabulary=movie_titles_vocabulary.get_vocabulary(),
    mask_token=None,
    invert=True)

print(f"Top titles for user: {index_to_title(top_movie_indices)}")
```

You can paste this straight into the quickstart colab to verify.

**Comment by nialloh23** [comment]
Thanks for the detailed answer & finding my small mistake @maciejkula 
Good to know that the recommended approach is to use the BruteForce layer with large num_candidates for situations like this. 

Great job launching this new library (from a previous lightfm fan!)
