### ISSUE TITLE
User model with UNK tokens

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/recommenders#108]
I have seen from the tutorial that you add a `+1` to take in account missing tokens like in the example here:

```python
user_model = tf.keras.Sequential([
  tf.keras.layers.experimental.preprocessing.StringLookup(
      vocabulary=unique_user_ids, mask_token=None),
  # We add an additional embedding to account for unknown tokens.
  tf.keras.layers.Embedding(len(unique_user_ids) + 1, embedding_dimension)
])
```

Now, in my User model, I have users with missing features, like missing `age`, therefore I may have

```python
ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
    "timestamp": x["timestamp"],
    "age": x["age"],
})
```

where age may have a `NULL` value (because it is missing). So will it be considered as a `OOV / UNK` token automatically if I do like:

```python
 self.age_embedding = tf.keras.Sequential([
        tf.keras.layers.experimental.preprocessing.Discretization(age_buckets.tolist()),
        tf.keras.layers.Embedding(len(age_buckets) + 1, 16),
    ])
```

**Comment by maciejkula** [comment]
Is `age` a numerical features? If yes, I don't think it can contain a `NULL` value.

If it's a string value and you use a `StringLookup` layer, any value (including `"NULL"`) you have in your vocabulary is treated in the same way; it's only tokens that are not present in the vocabulary that get the `OOV / UNK` treatment.

**Comment by loretoparisi** [comment]
@maciejkula thanks, it's just an example, so in a case of string it's clear to me, bur for a numerical feature (like age), which should be the right approach when that feature is not defined, while the other ones are?

Thank you.

**Comment by maciejkula** [comment]
As far as I know `Discretization` does not handle missing values.

To start with, you could go with `IntegerLookup` after encoding your missing values as a special integer, say -1?
