### ISSUE TITLE
How do user model and movie model relate in retrieval example?

### ISSUE THREAD

**Issue by gaolingxiao** [tensorflow/recommenders#117]
In the retrieval example, the user model is created with user ids 
```python 
user_model = tf.keras.Sequential([
  tf.keras.layers.experimental.preprocessing.StringLookup(
      vocabulary=unique_user_ids, mask_token=None),
  tf.keras.layers.Embedding(len(unique_user_ids) + 1, embedding_dimension)
])
```

The movie model is created with movie titles
```python
movie_model = tf.keras.Sequential([
  tf.keras.layers.experimental.preprocessing.StringLookup(
      vocabulary=unique_movie_titles, mask_token=None),
  tf.keras.layers.Embedding(len(unique_movie_titles) + 1, embedding_dimension)
])
```

I thought the example wants to build a relation between user id and movie title when seeing this code.
```python
ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
})
movies = movies.map(lambda x: x["movie_title"])
```

But then the example only keeps user id in ratings
```python
user_ids = ratings.batch(1_000_000).map(lambda x: x["user_id"])
```
I am confused that how these two properties relate to each other if we don't know the corresponding movie title of that user id.

**Comment by maciejkula** [comment]
The `user_ids = ratings.batch(...)` line you mention is only used to create a vocabulary for user ids. What actually gets passed into model training are pairs of user id and movie title, as shown in the `ratings = ratings.map(lambda x:...)` line in what you pasted above.
