### ISSUE TITLE
model.predict in colab DNN

### ISSUE THREAD

**Issue by adriendod** [tensorflow/recommenders#120]
Sorry for the beginner issue but I am doing the DNN colab and I'm just trying to make a prediction.
What data format/shape am i supposed to pass in model.predict to get a prediction as I keep getting this error :

 NotImplementedError: When subclassing the `Model` class, you should implement a `call` method.

Thank you

**Comment by anisayari** [comment]
It look like you do not have a function call() in your class Model. 

Can you please details your question and your call method (if it exist) as we do not know the format of your input? Please 
Do you use examples of this repo ? If yes which one ?

**Comment by adriendod** [comment]
Hello,
Yes i am using the colab DNN with the movielens data. I do not have a call function, you're right, could you refer me to an example please?

Thank you !

(sorry i do not know how to edit the issue to add a label )

**Comment by maciejkula** [comment]
If you're trying to build a retrieval model, you should construct a top-K retrieval layer and use that layer's `call` method to predict.

This is described [here](https://www.tensorflow.org/recommenders/examples/basic_retrieval#making_predictions) in our retrieval tutorial.

**Comment by adriendod** [comment]
thank you!

**Comment by adriendod** [comment]
So I added this and I get a concatenation issue :

```
# Create a model that takes in raw query features, and
index = tfrs.layers.factorized_top_k.BruteForce(model.query_model)
# recommends movies out of the entire movies dataset.
index.index(movies.batch(100).map(model.candidate_model), movies)

# Get recommendations.
_, titles = index({"user_id": tf.constant("346"), "timestamp": tf.constant(874948475)})
print(f"Recommendations for user 42: {titles[0, :3]}")
```

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

**Comment by adriendod** [comment]
found help here :) thanks!

https://github.com/tensorflow/recommenders/issues/87
