### ISSUE TITLE
 KeyError: 'user_id'

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/recommenders#121]
tensorflow.python.autograph.pyct.errors.KeyError: in converted code:

    main.py:18 None  *
        "movie_title": x["movie_title"],

    KeyError: 'user_id'

**Comment by maciejkula** [comment]
It looks like you're trying to look up a key in a dictionary that doesn't have a corresponding value.

If you'd like more meaningful help, could you provide more details, like the code you are running?
