### ISSUE TITLE
ValueError: The model cannot be compiled because it has no loss to optimize.

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/recommenders#122]
i run quickStart，but get this error when fitting model:
ValueError: The model cannot be compiled because it has no loss to optimize.

**Comment by maciejkula** [comment]
Did you run the quickstart colab at https://www.tensorflow.org/recommenders/examples/quickstart?

**Comment by juliobguedes** [comment]
I ran it recently and it seems to be working as intended. Did you try to run the entire notebook?

**Comment by ziliangok** [comment]
I have ran two examples, they are work well.
Based on your describe, it looks like you do not run
```
# Define your objectives.
task = tfrs.tasks.Retrieval(metrics=tfrs.metrics.FactorizedTopK(
    movies.batch(128).map(movie_model)
  )
)
```
