### ISSUE TITLE
Making predictions with features embedding and Dense Layers

### ISSUE THREAD

**Issue by anisayari** [tensorflow/recommenders#128]
Hello , 
I am currently following the notebook example : [context_features.ipynb](https://github.com/tensorflow/recommenders/blob/main/docs/examples/context_features.ipynb) . 

After the model is trained I am trying to make prediction from a new input. 

I am bulding my input as following in order to get a single input with a` timestamp` and a `user_id`: 

```
prediction_dataset = (
    tf.data.Dataset.from_tensor_slices(
        (
            tf.cast([1558656000], tf.int64),            
            tf.cast(['42'], tf.string),
        )
    )
)

prediction_tensor = prediction_dataset.map(lambda x,y: {
    "timestamp":x,
    "user_id":y,
})
```

But when I am trying to make prediction (like in [basic_retrieval.ipynb](https://github.com/tensorflow/recommenders/blob/main/docs/examples/basic_retrieval.ipynb)
Doing : 

```
index = tfrs.layers.factorized_top_k.BruteForce(UserModel(use_timestamps=True))
index.index(movies.batch(100).map(MovieModel()), movies)

# Get recommendations.
for pred in prediction_tensor.take(1):
    _, titles = index(pred)
    print(f"Recommendations for user 42: {titles[0, :3]}")
```

I am getting this error : 
`InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat`

And when I am trying to use the `model.predict()` function on my `prediction_tensor` : 

```
model.predict(prediction_tensor)
```
I am getting this error : 
```NotImplementedError: When subclassing the `Model` class, you should implement a `call` method.```

Please can you advice me how can I run prediction here ? Maybe I am doing something wrong here but i am stucked with this error for 2 days now. Any help will be really appreciated. Maybe we could update the notebook deep_recommenders with a section `Making predictions` as well.

**Comment by anisayari** [comment]
I was able to debug and making prediction doing : 
```
index = tfrs.layers.factorized_top_k.BruteForce(model.query_model)
index.index(movies.batch(100).map(model.candidate_model), movies)

# Get recommendations.
for pred in prediction_tensor.batch(1).take(1):
    _, titles = index(pred)
    print(f"Recommendations : {titles[0, :3]}")
```

Using issue #87 

Maybe we could add this section "Making prediction" in the notebook.

**Comment by maciejkula** [comment]
This is a rough edge of Keras: it always expects at least rank-2 tensors in `call`, and so you need to batch your inputs (as you have discovered).

**Comment by igorkf** [comment]
Hi! Thanks for the awesome package.

I used this to get the recommended items: 
```
nn = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
nn.index(items.batch(100).map(model.item_model))

for row in users.batch(1).take(2):
    print(nn(row)[1].numpy()[0].tolist())
```
It gives me a list of indices (that I imagine that are items indexes).   
How can I get now the items itself (not the indexes)?

**Comment by maciejkula** [comment]
@igorkf you need to pass two arguments to `index`: the embeddings and the identifiers. You're only passing one.

**Comment by igorkf** [comment]
@maciejkula  thanks for helping me.   
I excluded the second argument from `index` because it was returning scores instead of indexes. So I wrote in the documentation this https://github.com/tensorflow/recommenders/blob/v0.3.0/tensorflow_recommenders/layers/factorized_top_k.py#L296-L350:
```
Args:
      candidates: Matrix (or dataset) of candidate embeddings.
      identifiers: Optional tensor (or dataset) of candidate identifiers. If
        given these will be return to identify top candidates when performing
        searches. If not given, indices into the candidates tensor will be given
        instead.
```
Is this right?

**Comment by maciejkula** [comment]
Have a look at this [tutorial](https://www.tensorflow.org/recommenders/examples/basic_retrieval#making_predictions): the `BruteForce` layer returns a tuple of `(scores, identifiers)` if you supply `identifiers` to `index`. If you don't, it'll return indices.
