### ISSUE TITLE
Saving user_model for serving (Serialized keras model Vs TF SavedModel)

### ISSUE THREAD

**Issue by nialloh23** [tensorflow/recommenders#129]
In the [retrieval tutorial](https://www.tensorflow.org/recommenders/examples/basic_retrieval) it says that **'we can either serialize the Keras model directly'** or **export it to a SavedModel format**. 

But when I try to save the model.user_model as a keras h5 file as follows:
```
with tempfile.TemporaryDirectory() as tmp:
  path = os.path.join(tmp, "query_model")
  model.user_model.save(filepath=path,save_format='h5')

```

I get the following error:

```
NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer StringLookup with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7f0b8c1fe518>]
```

I notice in the keras documentation it states:
```
Models built with the Sequential and Functional API can be saved to both the HDF5 and SavedModel formats. Subclassed models can only be saved with the SavedModel format.
```

**Questions:**
1. Can we save the user_model as a single keras (.h5 file)? And if so what is wrong with the implementation above? This [tf saving guide](https://www.tensorflow.org/guide/keras/save_and_serialize) mentions that In order to save/load a model with a subclassed model, you should overwrite the get_config and optionally from_config methods?

2. If we have to save the user_model as a TF SavedModel format it would appear that we need to have the full directory of info ((i.e. a directory of assets, saved_model.pb, variables) in place to load the model back into memory. We typically push trained models, indices etc. to S3 buckets for eventual downloading and serving? Having to save, publish, download and recreate a full directory structure for TF Saved Model data seems overly complicated? Is there an easier way that I'm not thinking of...eg. tar/zip directory?

Thanks for any guidance on the above. 
Being able to encapsulate model.user_model in a single keras .h5 model would really make our lives a lot easier :)

**Comment by maciejkula** [comment]
1. I believe saving to `h5` is a discouraged path, and some new Keras layers (like `StringLookup`) do not work with this format. I suspect that removing this layer from your model would give you the `h5` path back, but you would lose the convenience (and consistency advantages) of having the vocab lookup as part of your model.
2. The `SavedModel` format is the way to go. I think zipping the directory at training and unzipping at the other end makes sense.

I definitely see the advantages of having a single file - but zipping/unzipping should be a relatively small change to your deployment infra (I know full well that nothing is ever as simple as it seems :)).

**Comment by nialloh23** [comment]
Thanks for clearing up @maciejkula . 
I'm going to go down the zipping/un-zipping root with the TF Saved Model.

**Comment by cfregly** [comment]
@maciejkula is there an example of saving and restoring any of these models for use with TF Serving?

I was stuck on this recently, as well, as I couldn’t find any good examples.  

I saw the same Keras save issues - especially with the custom Keras models that encapsulate the User and Model Keras models.

Any links to samples would be awesome.  Maybe I missed them?

**Comment by maciejkula** [comment]
For making predictions out of a two-tower retrieval model you should use the approach described [here](https://www.tensorflow.org/recommenders/examples/basic_retrieval#making_predictions).

You can export the entire `BruteForce` index to a `SavedModel` and load that in TF serving.

**Comment by maciejkula** [comment]
This is assuming that you're happy with brute force; if you'd like to use Annoy, you would export the user model only to a `SavedModel` and feed its output to your Annoy index (as described in the same tutorial).

We have some exciting developments that make all this easier slated for the next release, coming out in mid-November.

**Comment by cfregly** [comment]
yeah, ideally, there would be an example that passes a `user_id` to tensorflow serving and returns a list of `movie_id`.  this is the minimum loveable product (MLP) demo, in my opinion

**Comment by maciejkula** [comment]
Love the concept of a Minimum Loveable Product :+1: 

At the moment, the `BruteForce` approach does exactly that: creating the `BruteForce` layer instance and exporting it to serving has that exact interface, user id in, movie title out. Let me update the tutorial to point this out more prominently and ping here with the PR.

As I mentioned, we'll have something a whole lot more loveable soon :)

**Comment by maciejkula** [comment]
@cfregly updated the tutorial in https://github.com/tensorflow/recommenders/pull/133
