### ISSUE TITLE
validation metrics (like 'val_factorized_top_k/top_100_categorical_accuracy') does not appear in the history dictionary

### ISSUE THREAD

**Issue by xei** [tensorflow/recommenders#132]
Even running the following notebook has some errors:
https://colab.research.google.com/github/tensorflow/recommenders/blob/main/docs/examples/deep_recommenders.ipynb

KeyError                                  Traceback (most recent call last)
<ipython-input-12-e89ef6477a42> in <module>()
     11     verbose=0)
     12 
---> 13 accuracy = one_layer_history.history["val_factorized_top_k/top_100_categorical_accuracy"][-1]
     14 print(f"Top-100 accuracy: {accuracy:.2f}.")

KeyError: 'val_factorized_top_k/top_100_categorical_accuracy'

**Comment by maciejkula** [comment]
Just ran this notebook on Google Colab and it run correctly. Perhaps you're using an older version of TensorFlow?

**Comment by maciejkula** [comment]
Let me know if I can help more with this - closing for now but feel free to reopen.

**Comment by xei** [comment]
> Just ran this notebook on Google Colab and it run correctly. Perhaps you're using an older version of TensorFlow?

No it doesn't.
Clicking on the url I shared will open the notebook in Google colab. Just run it all once without any changes.
It has an error when you are trying to get "val_" value from the history.
I dout it if anyone can run it without error

**Comment by maciejkula** [comment]
I tried your link again and everything works.

One possibility is that somehow the VM on which your Colab runs has an older version of TensorFlow Recommenders installed. Can you try running the following at the beginning of your notebook?

```
!pip install --upgrade -q tensorflow-recommenders
```

**Comment by xei** [comment]
I added the "--upgrade" switch to get the latest version but unfortunately, nothing changed.

![screenshot](https://drive.google.com/file/d/1AAK3TMxIxHyMzneZ8eh2RGX0i7OqLvH6/view?usp=sharing)

**Comment by maciejkula** [comment]
You seem to have modified the number of epoch to 1 (from 300).

Because the validation runs every 5 epochs you'll need to run at least 5 epochs to get any validation.

**Comment by xei** [comment]
Oh. You are right. Thank you so much.

**Comment by siyu1992** [comment]
@maciejkula 
I just face the same issue, I set validation_freq=1, but validation metrics does not appear in the history dictionary

It seems that evaluation doesn't work. 

when I call model.evaluate(), overflowerror came out as follows:

`model.evaluate(cached_test_new, return_dict=True)

D:\Anaconda3\lib\site-packages\keras\utils\generic_utils.py:915: RuntimeWarning: divide by zero encountered in log10
  numdigits = int(np.log10(self.target)) + 1
Traceback (most recent call last):
  Debug Console, prompt 21, line 1
    # -*- coding: utf-8 -*-
  File "D:\Anaconda3\Lib\site-packages\keras\engine\training.py", line 1508, in evaluate
    callbacks.on_test_end(logs=logs)
  File "D:\Anaconda3\Lib\site-packages\keras\callbacks.py", line 523, in on_test_end
    callback.on_test_end(logs)
  File "D:\Anaconda3\Lib\site-packages\keras\callbacks.py", line 1043, in on_test_end
    self._finalize_progbar(logs, self._test_step)
  File "D:\Anaconda3\Lib\site-packages\keras\callbacks.py", line 1112, in _finalize_progbar
    self.progbar.update(self.target, list(logs.items()), finalize=True)
  File "D:\Anaconda3\Lib\site-packages\keras\utils\generic_utils.py", line 915, in update
    numdigits = int(np.log10(self.target)) + 1
builtins.OverflowError: cannot convert float infinity to integer`
