### ISSUE TITLE
Online learning with tensorflow recommenders and serving

### ISSUE THREAD

**Issue by urwrstkn8mare** [tensorflow/recommenders#143]
How do I serve a model with online learning, as in it learns in realtime with new input and outputs up to date recommendations for the user? And is that best practice, if not what is? 

This is not an issue, just a question I've had for a while. For context, I am talking about a movie recommender but should apply in any context I think.

**Comment by maciejkula** [comment]
The usual solution is to have a training job running a couple of times a day, and exporting new serving models at specified intervals (say, every hour). These would then be automatically pushed to serving.

**Comment by urwrstkn8mare** [comment]
Thanks!
