### ISSUE TITLE
FactorizedTopK candidates need to be unique?

### ISSUE THREAD

**Issue by urwrstkn8mare** [tensorflow/recommenders#144]
I was just wondering if the `candidates=` value in `tfrs.metrics.FactorizedTopK` as a metric for the `tfrs.tasks.Retrieval` have to be unique movies. As in the dataset can't have duplicates?

**Comment by maciejkula** [comment]
No - entirely up to you what you supply.

But I don't think it makes sense to have duplicates.

**Comment by urwrstkn8mare** [comment]
Thnx
