### ISSUE TITLE
The dtype of the source tensor must be floating (e.g. tf.float32) when calling ...

### ISSUE THREAD

**Issue by Flipper-afk** [tensorflow/recommenders#145]
Hi, fantastic libary!

I would like to ask, especially when it comes to "visually output optimization", if a dtype switch like `tf.cast(dtype)` can avoid the Warning Outputs or would the counter variable gets updated during GradientTape, even when` trainable=None`?

Idea(s):

```
In: layers/factorized_top_k.py

self._counter = self.add_weight("counter", dtype=tf.float32, trainable=None)      
...
def enumerate_rows(batch: tf.Tensor) -> Tuple[tf.Tensor, tf.Tensor]:
  ....
  end_counter = self._counter.assign_add(tf.dtypes.cast(tf.shape(batch)[0], tf.float32))
  return tf.dtypes.cast(tf.range(starting_counter, end_counter), tf.int32), batch

```
  
Looking forward faszinated,
Flipper

**Comment by maciejkula** [comment]
I think this has been resolved with #192 .
