### ISSUE TITLE
Shape must be rank 2 but is rank 1 during model.fit

### ISSUE THREAD

**Issue by italodamato** [tensorflow/recommenders#154]
I'm applying [this basic tutorial](https://www.tensorflow.org/recommenders/examples/basic_retrieval) to my dataset but I'm getting a shape error when fitting the model. What could be causing the problem? The shape of the `user_embeddings` and `positive_movie_embeddings` match like in the tutorial.

Thanks for your help 👍 

<details>
<summary>Full error here</summary>

Epoch 1/3
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-163-8662c7e7e10b> in <module>()
      5 cached_test = test_ds.batch(4096).cache()
      6 
----> 7 model.fit(train_ds, epochs=3)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow_recommenders/tasks/retrieval.py:126 call  *
        scores = tf.linalg.matmul(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3255 matmul
        a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py:5642 mat_mul
        name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:593 _create_op_internal
        compute_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:3485 _create_op_internal
        op_def=op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1975 __init__
        control_input_ops, op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Shape must be rank 2 but is rank 1 for '{{node retrieval_3/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=true](sequential_6/embedding_6/embedding_lookup/Identity_1, sequential_7/embedding_7/embedding_lookup/Identity_1)' with input shapes: [32], [32].

</details>

**Comment by Flipper-afk** [comment]
Looks like you're fitting the model with the un-batched dataset. Try to use the batched "cached_train" data

cached_test = test_ds.batch(4096).cache()
model.fit(`train_ds`, epochs=3)

assuming, there's also:
`cached_train = train_ds.batch(xxx).cache()`
=> model.fit(`cached_train`, epochs=3)
