### ISSUE TITLE
Can I use `scann` on Windows.

### ISSUE THREAD

**Issue by urwrstkn8mare** [tensorflow/recommenders#167]
Hi, I'm not sure but am I able to install [`scann`](https://github.com/google-research/google-research/tree/master/scann) on Windows. `pip` says it can't find it and I read [here](https://github.com/google-research/google-research/tree/master/scann#installation): "manylinux2014-compatible wheels are available on PyPI". Does that mean its only available for Linux? Any clarification would be appreciated.

**Comment by maciejkula** [comment]
Sorry - only on Linux.

I would suggest using Docker, or perhaps WSL.

@sammymax FYI.

**Comment by urwrstkn8mare** [comment]
Thnx
