### ISSUE TITLE
Scalabilty of tutorial code

### ISSUE THREAD

**Issue by fgvenegas** [tensorflow/recommenders#178]
Hello,

I was using the [tutorial code](https://www.tensorflow.org/recommenders/examples/quickstart) of the quick start guide but with around 35 millions of interaction between users and movies. The problem is that it takes a lot of hours to run just one single epoch even using a GPU. So I checked the performance of the code with [Tensorflow Profiler](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras?hl=en#setup) and noticed that there is a lot of use of CPU during training (There is no much difference in using or not GPU) probably during the mapping of the data (I don't understand completely the Trace View). 

So the question is ¿there is a way to improve the original code to work faster with big amounts of data?

These are screenshots of the Profiler:

<img width="771" alt="Captura de Pantalla 2020-12-01 a la(s) 18 38 29" src="https://user-images.githubusercontent.com/13748708/100799942-a18fc700-3404-11eb-8a7b-b7eaecf6a10b.png">
<img width="1104" alt="Captura de Pantalla 2020-12-01 a la(s) 18 39 30" src="https://user-images.githubusercontent.com/13748708/100799946-a3598a80-3404-11eb-9330-78a85331ad8d.png">

Thanks a lot!

**Comment by maciejkula** [comment]
The first thing to do is to not compute evaluation metrics during training. To do so, pass `compute_metrics=not training` to the task invocation in compute loss.

**Comment by fgvenegas** [comment]
@maciejkula That make a huge difference! Thanks
