### ISSUE TITLE
How to add items features in retrieval and predict movie_id ? 

### ISSUE THREAD

**Issue by anisayari** [tensorflow/recommenders#179]
First of all, thank you for taking the time to read me.

Based on the [deep_recommenders tutorials](https://colab.research.google.com/github/tensorflow/recommenders/blob/main/docs/examples/deep_recommenders.ipynb#scrollTo=NkoLkiQdK4Um)

I want to predict the movie_id (considering it is a string) and still using the movie_title as a side feature.

I am constructed my dataset like : 
```
ratings = tfds.load("movielens/100k-ratings", split="train")
movies = tfds.load("movielens/100k-movies", split="train")

ratings = ratings.map(lambda x: {
    "movie_id": x["movie_id"]
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
    "timestamp": x["timestamp"],
})
movies = movies.map(lambda x: {
"movie_title": x["movie_title"],
"movie_id": x["movie_id"]
})
```

My MovieLens model : 

```
class MovieModel(tf.keras.Model):
  
  def __init__(self):
    super().__init__()

    max_tokens = 10_000

    #------ EMBEDDING ID 
    self.id_embedding = tf.keras.Sequential([
      tf.keras.layers.experimental.preprocessing.StringLookup(
          vocabulary=unique_movie_ids,mask_token=None),
      tf.keras.layers.Embedding(len(unique_movie_id) + 1, 32)
    ])

    #------ EMBEDDING TITLE
    self.title_embedding = tf.keras.Sequential([
      tf.keras.layers.experimental.preprocessing.StringLookup(
          vocabulary=unique_movie_title,mask_token=None),
      tf.keras.layers.Embedding(len(unique_movie_title) + 1, 32)
    ])

    self.title_vectorizer = tf.keras.layers.experimental.preprocessing.TextVectorization(
        max_tokens=max_tokens)

    self.title_text_embedding = tf.keras.Sequential([
      self.title_vectorizer,
      tf.keras.layers.Embedding(max_tokens, 32, mask_zero=True),
      tf.keras.layers.GlobalAveragePooling1D(),
    ])

    self.title_vectorizer.adapt(movies.map(lambda x: x["movie_title"]).batch(1024))

  def call(self, inputs):
    return tf.concat([
        self.id_embedding(inputs['movie_id']),
        self.title_embedding(inputs['movie_title']),
        self.title_text_embedding(inputs['movie_title']),
    ], axis=1)
```

and my prediction : 
```
nn = tfrs.layers.factorized_top_k.BruteForce(model.query_model)
nn.index(movies.batch(1024).map(model.candidate_model), identifiers=movies.map(lambda x: x["movie_title"]).batch(1024)))

for row in prediction_tensor.batch(1):
  print(f"Best recommendations: {nn(row)[1].numpy()[:, :7].tolist()}")
  print('next')
```

Return me always  7 times the same ID recommended for each row...

Something is wrong with my approach, any help will be highly appreciate. 

Thank you for taking the time to help me.

**Comment by maciejkula** [comment]
Would you mind putting this into a colab that I can run?

I'm not clear on a couple of things. For example, in indexing you use `model.candidate_model`, but that's not defined in the snippet you posted.

**Comment by Flipper-afk** [comment]
Looks like the `['movie_title']` get's passed into `self.id_text_embedding`.
Feel free to give `inputs['movie_id']` a try
```
    return tf.concat([
        ...
        self.id_text_embedding(inputs['movie_id']),
    ], axis=1)
```

**Comment by anisayari** [comment]
> Would you mind putting this into a colab that I can run?
> 
> I'm not clear on a couple of things. For example, in indexing you use `model.candidate_model`, but that's not defined in the snippet you posted.

I did this notebook example : https://colab.research.google.com/drive/1Z9SM23eAJkmIV3C0VTbizSv_ORQeRoDT?usp=sharing

During doing I think I thought the issue, why my model was recommended me for example : `['1457','1457','1457','1457','1457','1457','1457']`. 

It was because I constructed the `movies` from ratings doing : 
```
movies= ratings.map(lambda x: {
    "movie_id": x["movie_id"],
    "movie_title": x["movie_title"],
})
```

Making the index and the identifiers not unique for prediction. And creating the side effect I was not wishing for.

**Comment by anisayari** [comment]
> Looks like the `['movie_title']` get's passed into `self.id_text_embedding`.
> Feel free to give `inputs['movie_id']` a try
> 
> ```
>     return tf.concat([
>         ...
>         self.id_text_embedding(inputs['movie_id']),
>     ], axis=1)
> ```

Thank you for the review. It was a typo , I updated my message with correction :-)

**Comment by maciejkula** [comment]
Apologies if I'm getting this wrong: it looks like this is solved?
