### ISSUE TITLE
[Question]: why same dataset has errors when fit the model, but can be passed in the subclass models?

### ISSUE THREAD

**Issue by ZheZhangTUD** [tensorflow/recommenders#185]
Hi, I am trying to use my dataset to build a simple ranking model. 
Firstly, my input dataset is a dictionary including three arrays "userID" "newsID" "category" "label".
Second, I follow the documents of ranking in tfrs to build the Ranking model, including the sub Ranking model(compute the embedding), the NewslensModel( which is almost same with the original document's code, add the loss and metric).
Third, before this, all is fine. my dataset can pass the Ranking model and compute loss function in NewslensModel, But It has errors when I use the same dataset to fit model, it appear "TypeError: tuple indices must be integers or slices, not str", and I tried to set the dictionary's keys as int, it doesn't work. Could you give me some help? Thanks.
Picture ONE is the error when fit model, Two is the dataset , return the result of compute loss function and sub ranking model.
![image](https://user-images.githubusercontent.com/32434163/102026631-e74e7700-3d96-11eb-992a-76deb1701d92.png)
![image](https://user-images.githubusercontent.com/32434163/102026731-73f93500-3d97-11eb-8310-6ed31ddce70a.png)

**Comment by maciejkula** [comment]
Could you reproduce this in a minimal colab that I could run?

**Comment by maciejkula** [comment]
Closing: please feel free to reopen once you have a colab.
