### ISSUE TITLE
Confirming approach in comparison with the Research paper.

### ISSUE THREAD

**Issue by anisayari** [tensorflow/recommenders#195]
In the research paper from Tensorflow Recommender Doc https://storage.googleapis.com/pub-tools-public-publication-data/pdf/6c8a86c981a62b0126a11896b7f6ae0dae4c3566.pdf, we can notice that they are passing candidate features to the query model as well. 
![image](https://user-images.githubusercontent.com/10380894/103170598-a732ce00-4845-11eb-9c54-05fea610d583.png)

Otherwise in the example provided in the tensorflow recommenders library only user features are passing to the query model and movies features to the candidates model.  Like for example in the [deep recommender ](https://github.com/tensorflow/recommenders/blob/main/docs/examples/deep_recommenders.ipynb) example : 

```
 query_embeddings = self.query_model({
        "user_id": features["user_id"],
        "timestamp": features["timestamp"],
    })
    movie_embeddings = self.candidate_model(features["movie_title"])
```

Is it normal and do we expect this behavior coming from the Retrieval task ? Or can we use candidates features in the query models as well ? Any indication whenever each approach should be used will be really appreciated . Thank you.

**Comment by maciejkula** [comment]
Looking at the image you linked to candidate features _are not_ passed to the query model.

The inputs to the query model include features of the user (what they watched in the past) and features of the current video they are watching (seed video). See section 5 for the explanation.

In general, the retrieval task handles factorized models where candidate features are never passed to the query model. This is what enables efficient approximate serving.

**Comment by anisayari** [comment]
You are totally right. Sorry for this confusion. Thank you.
