### ISSUE TITLE
Number of candidates to retrieve doesn't work

### ISSUE THREAD

**Issue by litlife** [tensorflow/recommenders#196]
After saving and loading the BruteForce model, if you request candidates and specify the number, an error appears.
I took an example from the documentation and entered the number of candidates
https://colab.research.google.com/drive/1hkmYMEbDocJwJU4mCwAHU1fehbPtsCf-?usp=sharing
```
with tempfile.TemporaryDirectory() as tmp:

    path = os.path.join(tmp, "model")

    index.save(path)

    loaded = tf.keras.models.load_model(path)

    scores, titles = loaded(["42"], k=20)

    print(f"Recommendations: {titles[0][:3]}")
```
And I get this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-bbf068f09fa1> in <module>()
     10 
     11   # Pass a user id in, get top predicted movie titles back.
---> 12   scores, titles = loaded(["42"], k=20)
     13 
     14   print(f"Recommendations: {titles[0][:3]}")

15 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/function_deserialization.py in restored_function_body(*args, **kwargs)
    255         .format(_pretty_format_positional(args), kwargs,
    256                 len(saved_function.concrete_functions),
--> 257                 "\n\n".join(signature_descriptions)))
    258 
    259   concrete_function_objects = []

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (3 total):
    * ['42']
    * 20
    * False
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * TensorSpec(shape=(None,), dtype=tf.string, name='queries')
    * None
    * True
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * TensorSpec(shape=(None,), dtype=tf.string, name='input_1')
    * None
    * False
  Keyword arguments: {}

Option 3:
  Positional arguments (3 total):
    * TensorSpec(shape=(None,), dtype=tf.string, name='queries')
    * None
    * False
  Keyword arguments: {}

Option 4:
  Positional arguments (3 total):
    * TensorSpec(shape=(None,), dtype=tf.string, name='input_1')
    * None
    * True
  Keyword arguments: {}
```
The same error appears for ScaNN

**Comment by anisayari** [comment]
I think you have to save the model with the desired number of k you are looking for to retrieve, you cannot change later  the k number as you are trying to do, as all arguments in `loaded( )` will be passed to the model and not in the initialization of the bruteforce., and  `k=' is not an appropriate argument to be passed as the error suggest. 

`index = tfrs.layers.factorized_top_k.BruteForce(model.user_model, k = 20)`
 after save and make prediction on the k you are looking for. 
 
 You may think, "oh ok but why i dont give a number of k and after truncated the list ? You could but your prediction will be slower to make. 

 
 Doc : https://www.tensorflow.org/recommenders/api_docs/python/tfrs/layers/factorized_top_k/BruteForce

**Comment by litlife** [comment]
Thank you, @anisayari ! Perhaps my question relates to this question https://github.com/tensorflow/recommenders/issues/171#issuecomment-731871441
