### ISSUE TITLE
can't install scann on Mac

### ISSUE THREAD

**Issue by italodamato** [tensorflow/recommenders#212]
I've followed [this guide](https://dev.to/eugeneyan/how-to-install-google-s-scalable-nearest-neighbors-scann-on-mac-64l) since `pip install scann` was failing with this error 
```
ERROR: Could not find a version that satisfies the requirement scann
ERROR: No matching distribution found for scann
```

I can now import scann and instantiate the object correctly but as soon as I try to call the `index()` method, it keeps loading forever while my CPU/memory is not used at all. It gets stuck also on this tutorial https://www.tensorflow.org/recommenders/examples/basic_retrieval

Is there a way to properly install the package?

**Comment by maciejkula** [comment]
You'll need to use Docker - I'm afraid ScaNN is not available on other operating systems.

**Comment by whiteXY7** [comment]
I can't install scann on my windows , either.
So if this means I run the following codes?
Is there another package to replace scann?

**Comment by maciejkula** [comment]
Please consider using ScaNN with Docker or a similar solution. It has no pre-built wheels for systems other than Linux.
