### ISSUE TITLE
ScaNN index layer cannot be served through TF Serving docker container!

### ISSUE THREAD

**Issue by xei** [tensorflow/recommenders#216]
### request:
```
curl --location --request POST 'IP_ADDRESS:8501/v1/models/retrieval:predict' \
--header 'Content-Type: application/json' \
--data-raw '{
    "instances":
        [
            "42"
        ]
}'
```
### Response:
```
{
    "error": "Op type not registered 'Scann>ScannSearchBatched' in binary running on ea72279e0fdb. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed."
}
```

I also tried:
```
docker exec -it CONTAINER_ID  pip install scann
```

but:
```
ERROR: Could not find a version that satisfies the requirement scann
ERROR: No matching distribution found for scann
```

I think we have to copy over op source
https://github.com/google-research/google-research/blob/master/scann/scann/scann_ops/py/scann_ops.py

into Serving project
https://www.tensorflow.org/tfx/serving/custom_op#copy_over_op_source_into_serving_project

but I don't know how!
Can anybody help writing a custom Dockerfile?

**Comment by maciejkula** [comment]
It may be best to ask these questions in the https://github.com/tensorflow/serving issue tracker.

**Comment by xei** [comment]
> It may be best to ask these questions in the https://github.com/tensorflow/serving issue tracker.

TF is just a general library for machine learning, maybe a base library and TF Serving is a great solution to ease serving the final models.
However, TFRS is going to be an extension to TF aiming to develop/deploy practical recommender systems even more easily, so serving the models created by TFRS is TFRS' concern, not TF Serving!

**Comment by maciejkula** [comment]
I see your point! Unfortunately I myself am not familiar with the process of compiling new ops into serving. The guide you linked seems to be the canonical reference for this.

**Comment by sammymax** [comment]
I'll work on a ScaNN + TF Serving Dockerfile in the coming weeks--thanks for pointing this out!

**Comment by turnerneil** [comment]
Hello, I'm receiving the same error.

**Comment by sammymax** [comment]
The Dockerfiles are ready; they're on Docker Hub [here](https://hub.docker.com/r/google/tf-serving-scann) and instructions are [here](https://github.com/google-research/google-research/tree/master/scann/tf_serving). The Dockerfiles are in the linked GitHub directory, if you're interested in seeing how they're built.

These images were built on Clang-8 with C++17 and AVX2 enabled, while I believe the vanilla TF Serving images are built with GCC 7, C++11, and no AVX2. This means a AVX2-enabled CPU is required (any ~2013 or later x86 CPU should be ok). Otherwise, leave a comment if you run into any issues.

**Comment by xei** [comment]
> The Dockerfiles are ready; they're on Docker Hub [here](https://hub.docker.com/r/google/tf-serving-scann) and instructions are [here](https://github.com/google-research/google-research/tree/master/scann/tf_serving). The Dockerfiles are in the linked GitHub directory, if you're interested in seeing how they're built.
> 
> These images were built on Clang-8 with C++17 and AVX2 enabled, while I believe the vanilla TF Serving images are built with GCC 7, C++11, and no AVX2. This means a AVX2-enabled CPU is required (any ~2013 or later x86 CPU should be ok). Otherwise, leave a comment if you run into any issues.

Great job @sammymax, Thank you so much.
Now the TFRS is easily applicable in practice.
The next step that helps TFRS to be practical in production environments is to make an image ready to serve on GPUs.
I hope someone help doing this.
