### ISSUE TITLE
Is it possible to recommend only a subsample of candidates ? 

### ISSUE THREAD

**Issue by anisayari** [tensorflow/recommenders#225]
I am looking to recommend only a subsample of candidates regarding of the day of the prediction. 
For example 

- Day 1 I want to recommend only items 1 to 100
- Day 2 recommend only item 101 to 200
- Day 3 recomend only item 201 to 300

My question is simple (sorry if if it is a beginners question), but can the `candidates` dataset of `tfrs.metrics.FactorizedTopK` be a subsample of the training dataset  ? Is it something not recommended ? 
For example by doing :
```
metrics = tfrs.metrics.FactorizedTopK(
  candidates=movies.take(500).batch(128).map(movie_model)
)
```

instead of 

```
metrics = tfrs.metrics.FactorizedTopK(
  candidates=movies.batch(128).map(movie_model)
)
```

Or do you recommend to train on all candidates and to predict on the subsample during the bruteforce retrieveing method ?
By doing :
```
index = tfrs.layers.factorized_top_k.BruteForce(model.user_model)

index.index(movies.batch(100).map(model.movie_model), movies)
```

```
index = tfrs.layers.factorized_top_k.BruteForce(model.user_model)

index.index(movies.take(500).batch(100).map(model.movie_model), movies)
```

**Comment by maciejkula** [comment]
Using a subsample is exactly the correct solution.

**Comment by anisayari** [comment]
@maciejkula thank you for your answer.
But do you recommend to use a subsample during the training in “metrics” or at the initialization of the index in “index.index” during the prediction ?

**Comment by maciejkula** [comment]
One or both depending on what you want to serve and what you want to measure.

If you want to measure performance on a subset, change it in metrics. If you want do serve a subset, change the index. Any combination of the two also works :)
