### ISSUE TITLE
How to Extract Predictions from Building Deep Retrieval Models?

### ISSUE THREAD

**Issue by turnerneil** [tensorflow/recommenders#226]
The "[Building Deep Retrieval Models](https://www.tensorflow.org/recommenders/examples/deep_recommenders)" guide is informative, but there is no information about getting predictions. I've tried to apply the "BruteForce" method from other tutorials with no success.

I've also tried to use the predict method, which returns NotImplementedError: When subclassing the `Model` class, you should implement a `call` method.

**Comment by maciejkula** [comment]
The `BruteForce` or `ScaNN` methods from [this tutorial](https://www.tensorflow.org/recommenders/examples/efficient_serving) apply here equally. Perhaps you can share what went wrong with these approaches? One easy way of doing so is to modify the colab and share a link to it so that I could have a look.

**Comment by turnerneil** [comment]
@maciejkula Great Idea! Here is a modified colab: https://colab.research.google.com/drive/1s_tPMq6_qXxQmHRgZDWO5t_tCHPZO96K?usp=sharing

Side node: calculating accuracy fails in this colab, but I proceed to demonstrate how I attempted to get predictions.

**Comment by maciejkula** [comment]
Thanks for the notebook. The input to your model is a dictionary of array, so calling it like this works:

```python
_, titles = brute_force({
    "user_id": np.array(["138"]),
    "timestamp": np.array([879024327])},
    k=3
)
```

**Comment by turnerneil** [comment]
@maciejkula Perfect! I updated the modified colab notebook with the solution. Thank you.
