### ISSUE TITLE
[Question] Evaluation is extremely slow.

### ISSUE THREAD

**Issue by ydennisy** [tensorflow/recommenders#227]
Hi! (me again)

Evaluation is extremely slow, even when not using the retrieval top-k task. Looking at the system resources it only runs on CPU and in what looks like a single sequential loop. This is even when using a TF dataset.

Is there anyway to speed up the eval process?

Thanks in advance!

**Comment by maciejkula** [comment]
Is this for a retrieval model?

Have you seen [this section](https://www.tensorflow.org/recommenders/examples/efficient_serving#evaluating_the_approximation) on using the `BruteForce` and `ScaNN` layers to get orders-of-magnitude faster evaluation?

**Comment by ydennisy** [comment]
Hi @maciejkula no this is specifically for ranking only models.

**Comment by maciejkula** [comment]
Are you running the evaluation within your GPU device scope?

**Comment by ydennisy** [comment]
I am running the evaluation within the call to `model.fit()` by passing in `validation_data=`.

The trainer class looks like:
```python
class Trainer():
    def __init__(self):
        self.params = {
            'lr': 0.001,
            'train_lm': False,
            'query_embed_dims': 32,
            'candidate_embed_dims': 32
        }

    def set_params(self, **kwargs):
        self.params = kwargs
    
    def compile(self, domain_lookup, io_lookup):
        gpus = tf.config.list_physical_devices('GPU')

        if len(gpus) > 1:
            strategy = tf.distribute.MirroredStrategy()
        elif len(gpus) == 1:
            strategy = tf.distribute.OneDeviceStrategy(device='/gpu:0')
        else:
            strategy = tf.distribute.OneDeviceStrategy(device='/cpu:0')

        with strategy.scope():
            self.model = Model(
                domain_lookup, 
                io_lookup, 
                self.params['query_embed_dims'],
                self.params['train_lm']
            )

            self.model.compile(
                optimizer=tf.keras.optimizers.Adam(learning_rate=self.params['lr']))
                #steps_per_execution=10)

    def fit(self, train, val, meta, epochs=30, verbose=1):
        self.model.fit(
            train,
            epochs=epochs,
            verbose=verbose,
            validation_data=val,
            validation_steps=meta['num_val_batches'],
            steps_per_epoch=meta['num_train_batches'])
```

**Comment by maciejkula** [comment]
This looks fine to me - I cannot think of any reason why your model would run on the GPU in training but on CPU in eval.

**Comment by lukhaza** [comment]
Same issue here. Both model.evaluate and model.fit(validation_data=) are slow.

**Comment by aryansaurav** [comment]
Same issue with the evaluation called using callbacks. GPU is not being used.

**Comment by patrickorlando** [comment]
What metrics are you using @ydennisy?
Have you called `.prefetch(tf.data.AUTOTUNE)` on your datasets?
