### ISSUE TITLE
tensorflow-recommenders not backword compatible with Google AI Platform Training runtimes versions

### ISSUE THREAD

**Issue by turnerneil** [tensorflow/recommenders#228]
AI Platform Training runtimes versions (https://cloud.google.com/ai-platform/training/docs/runtime-version-list) do not support TensorFlow 2.4. Installing the most recent version of tensorflow-recommenders `pip install tensorflow-recommenders==0.4.0` causes the packaged training application to update tensorflow to version 2.4. This causes the machine to fail.

A solution, is to build models using an older version of tensorflow-recommenders that was build on tensorflow 2.3 (ex: tensorflow-recommenders==0.2.0). Another solution, is to pass the `--no-deps` argument in the pip install command. This work fine for ai platform notebooks, but I couldn't figure our how to apply the --no-deps solution to packaging my application for training.

**Comment by joseprsm** [comment]
My solution was to [use custom containers](https://cloud.google.com/ai-platform/training/docs/using-containers). That way you won't have to deal with dependencies.
