### ISSUE TITLE
Extracting candidate & user embeddings from retrieval model with context features

### ISSUE THREAD

**Issue by nialloh23** [tensorflow/recommenders#233]
**Context**
I'm training a candidate retrieval model that has context features (similar to the tutorial).
I want to extract the trained query (e.g. user embeddings) and candidate embeddings (e.g. products) from the model to: 
- use in downstream models
- Run PCA->clustering->TSNE visualizations
- Cluster analysis of similar candidates/users   

**Question:**   
My current approach (for candidate embeddings) is building a bruteforce index using the candidate model as the query model -> Then extracting the weights of the last two layers to get the labels & weights of the embeddings for each candidate. My question is whether or not this is the best way or makes sense? In the example code below I only pass the movie title through the candidate model to build the movie index but if there are more features I guess I would need to pass these here also?

```
index = tfrs.layers.factorized_top_k.BruteForce(model.candidate_model)  
index.index(movies.batch(100).map(model.candidate_model), movies)  

candidate_labels = index.get_weights()[-2]  
candidate_embeddings = index.get_weights()[-1]  

```

The other approach I had considered was just training the model and extracting the embeddings by directly accessing the layer weights in the network. In this instance I'm only getting the weights of the movie_ids in the context features tutorial but I'm not sure if this is better or worse than the approach above which includes the title embeddings.

`model.candidate_model.layers[0].get_weights()[2]`

**Comment by maciejkula** [comment]
The most direct way would be probably to do exactly what the `BruteForce` layer [does under the hood](https://github.com/tensorflow/recommenders/blob/main/tensorflow_recommenders/layers/factorized_top_k.py#L470): 

```python
candidates = tf.concat(list(movies.batch(100).map(model.candidate_model)), axis=0) 
```

Yes, you need to pass all the features your candidate model uses.

Extracting embedding weights will work, but only if you only have one feature - the method above is by far more general and preferable.

**Comment by nialloh23** [comment]
Thanks @maciejkula This approach worked perfectly. 
Thanks again.
