### ISSUE TITLE
Fix TFRS v0.4.0 dependency on TF

### ISSUE THREAD

**Issue by dgoldenberg-audiomack** [tensorflow/recommenders#271]
Noticing that in requirements.txt, it says:
```
tensorflow >= 2.3.0
```
however in setup.py it says:
```
REQUIRED_PACKAGES = [
    "absl-py >= 0.1.6",
    "tensorflow == 2.4.*",
]
```
The latter is on master however; on 0.4.0 it says:
```
REQUIRED_PACKAGES = [
    "absl-py >= 0.1.6",
    "tensorflow == 2.4",
]
```

It seems to me that the requirements and the required packages are somewhat at odds with each other. >= 2.3.0 vs. ==2.4.* seems not quite a full match and perhaps a source of user confusion.

Also, the 2.4.* is a recent thing; it's not in the 0.4.0 release.

If you install TF 2.4.1 first then TFRS, the TFRS install may wipe out TF 2.4.1 and install TF 2.4.0 instead.  Which may be a surprise if your code is using something like the `MultiWorkerMirroredStrategy` which is in TF 2.4.1 but not 2.4.0.

If you then install TFRS 0.4.0 first then TF 2.4.1 you get what looks like a non-fatal error from pip3:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-recommenders 0.4.0 requires tensorflow==2.4, but you have tensorflow 2.4.1 which is incompatible.
```
"Non-fatal" because TF 2.4.1 is installed anyway; so this seems more of a warning than a true error.

I'm not sure what, if anything could or should be changed. Thought I'd jot this down as more of an item for folks to comment on.

**Comment by maciejkula** [comment]
Thanks for pointing this out. We should remove `requirements.txt` because it's out of date.

**Comment by dgoldenberg-audiomack** [comment]
@maciejkula Sure. Did you mean, update `requirements.txt`? or actually remove it? seems like a standard thing, to have a requirements txt around..

**Comment by turnerneil** [comment]
I encountered a similar issue when running training jobs on the Google Cloud A.I platform (gcloud ai-platform job submit). 

The machine tries to reinstall  "absl-py >= 0.1.6" and "tensorflow == 2.4" which causes errors.

**Comment by maciejkula** [comment]
Thanks for reporting this issue - I'll be cutting a release next week and this will change to TF 2.4.*, then eventually to TF 2.5.* once we update ScaNN.

**Comment by dgoldenberg-audiomack** [comment]
TF 2.5.0 is out.

**Comment by mehdydousty** [comment]
I am facing the same issue. I have tf-GPU 2.4 installed, but tf-2.6 (CPU) version gets installed when I pip tensorflow-recommenders which causes issues in my code. So, I was wondering if there is a way to solve it

**Comment by MDOSTI** [comment]
I am facing the same issue. I have tf-GPU 2.4 installed, but tf-2.6 (CPU) version gets installed when I pip tensorflow-recommenders which causes issues in my code. So, I was wondering if there is a way to solve it

**Comment by maciejkula** [comment]
You can install an older version of TFRS that doesn't depend on TF2.6.

**Comment by maciejkula** [comment]
The original issue should now be fixed, and the requirements should be aligned.
