### ISSUE TITLE
Recommending similar products

### ISSUE THREAD

**Issue by Ullar-Kask** [tensorflow/recommenders#323]
Hi,
How to use the TFRS framework to recommend similar products? Currently, given a customer the framework can be used to recommend products (retrieved from the query index). But when a product is given can it be used to recommend "similar" products? Like drop the customer, recommend similar products (e.g. based on co-occurrence statistics). How to build the index in this case? I dont get meaningful results when I use product id both as a feature and as a label in training.

**Comment by alimirferdos** [comment]
You can use a nearest neighbour search algorithm to get similar items solely based on the item embedding. A choice may be [ANNOY](https://github.com/spotify/annoy) which is a fast library for querying the nearest vectors.

You can also find a relevant tutorial [here](https://github.com/tensorflow/hub/blob/master/examples/colab/tf2_semantic_approximate_nearest_neighbors.ipynb).

**Comment by Ullar-Kask** [comment]
Thanks a lot for the links!
