### ISSUE TITLE
Why is ScaNN slow for the first call after indexing?

### ISSUE THREAD

**Issue by shionhonda** [tensorflow/recommenders#325]
Hi, I read [the ScaNN tutorial](https://www.tensorflow.org/recommenders/examples/efficient_serving) and tried some custom settings. where I ran into a confusing phenomenon.

[This section](https://www.tensorflow.org/recommenders/examples/efficient_serving#approximate_prediction) says ScaNN is "much, much faster" than brute force.

|Algorithm|Inference time [ms]|
|:-:|:-:|
|Brute force|25.5|
|ScaNN|3.31|

But, **when I call the ScaNN model for the first time after indexing, it gets significantly slower (> 500 ms)**, even than brute force. Why does this happen?

# How to reproduce
First, follow the tutorial to this snippet:

```python
scann = tfrs.layers.factorized_top_k.ScaNN(num_reordering_candidates=1000)
scann.index(lots_of_movies_embeddings, lots_of_movies)
```

Then call the model in the next cell, and it will take more than 500 ms.

```python
%%time
_, titles = scann(model.user_model(np.array(["42"])), k=3)
# >> CPU times: user 452 ms, sys: 310 ms, total: 761 ms
# >> Wall time: 769 ms
```

Call it again with another query, and it behaves as expected.

```python
%%time
_, titles = scann(model.user_model(np.array(["43"])), k=3)
# >> CPU times: user 9.2 ms, sys: 0 ns, total: 9.2 ms
# >> Wall time: 13.9 ms
```

**Comment by maciejkula** [comment]
There is some initialization happening at first call. This is why it's good practice to warm up a new model with some dummy requests before exposing it to production traffic.

**Comment by shionhonda** [comment]
Thanks for answering.
Now I understand that it's a feature of eager mode!
