### ISSUE TITLE
How to load a pandas dataframe with tensorflow datasets

### ISSUE THREAD

**Issue by kleekaai** [tensorflow/recommenders#329]
I am working on recommendation engine and currently exploring tensorflow recommenders(link [here][1]). Can someone help in loading a dataframe. It has user_id , title and rating data similar to movielens dataset.

I have come across similar questions  that suggest to convert the datatype. I did that (np.asarray(data_subset).astype(np.float32)) but I still wasn`t able to feed it to tfds.load() function. 

My sample dataframe

    user_id	rating	title_id
    0	413	1	4364
    1	413	1	1071
    2	413	1	2223
    3	413	1	4598
    4	413	2	2950

Here is how movielens dataset is loaded using tensorflow utils. 

    # Load the MovieLens 100K data.
    ratings = tfds.load(
        "movielens/100k-ratings",
        split="train"
    )
    
    # Get the ratings data.
    ratings = (ratings
               # Retain only the fields we need.
               .map(lambda x: {"user_id": x["user_id"], "movie_title": x["movie_title"]})
               # Cache for efficiency.
               .cache(tempfile.NamedTemporaryFile().name)
    )
    
    # Get the movies data.
    movies = tfds.load("movielens/100k-movies", split="train")
    movies = (movies
              # Retain only the fields we need.
              .map(lambda x: x["movie_title"])
              # Cache for efficiency.
              .cache(tempfile.NamedTemporaryFile().name))

  [1]: https://www.tensorflow.org/recommenders/examples/efficient_serving

**Comment by maciejkula** [comment]
You wouldn't load a dataframe into TFDS - you would wrap it into a `tf.data.Dataset` object, likely through `tf.data.Dataset.from_tensor_slices`.
