### ISSUE TITLE
adapt()ing preprocessing layers 

### ISSUE THREAD

**Issue by Ullar-Kask** [tensorflow/recommenders#345]
Hi,
I have seen that in many cases some preprocessing layers are adapted with data (using the adapt() method), but in many cases they are not. Going through many examples it seems that the practice is inconsistent.
Are there any general guidelines when to adapt(), and when adapting is not necessary?
Thanks a lot!

**Comment by maciejkula** [comment]
Whatever is most convenient for you.

`adapt` works well if you don't have a lot of data: perhaps a couple of GB that you can easily iterate over.

If you have terabytes of data, you'll probably have a completely separate map-reduce cluster that will be constructing your vocabularies/`adapt`-like statistics.

**Comment by Ullar-Kask** [comment]
Thanks Maciej! I appreciate that!
