### ISSUE TITLE
How to use product side features?

### ISSUE THREAD

**Issue by Ullar-Kask** [tensorflow/recommenders#348]
What is the proper way of using product side features? Lets say I have a customer database, product database and transaction history database, and a recommender model to recommend products to customers. The model consists of a query model and a candidate model. As I understand, the general scheme is to use customer features and transaction data in the query model, and product features (side features ) in the candidate model. The question is: are there any reasons to use product side features in the query model? What use cases would benefit from it?

**Comment by maciejkula** [comment]
One common reason to use product features in the query tower is product page recommendations - say, related products.

If the user is currently viewing product X, the features of product X could be inputs to the query tower alongside other things we know about the user.
