### ISSUE TITLE
Item-to-item recommendation

### ISSUE THREAD

**Issue by max-grzanna** [tensorflow/recommenders#378]
The quick start guide says TFRS can also be used for item-to-item recommendations. In the retrieval guide, it says: "... and train the model using (query item, candidate item) pairs." If, for instance, my training data looks like this (containing product IDs from bought together items):

| product_one | product_two |
|-------------|-------------|
| 22          | 4442        |
| 22          | 7763        |
| 125986      | 1252        |
| ...         | ...         |

should the candidate tower only contain all the unique items from column two, or all the unique items across the whole dataset? 

How would a dataset look like for an item-to-item recommender?

Any response will be highly appreciated! :)

**Comment by maciejkula** [comment]
That's up to you!

One way to fit a model like this is to have a shared embedding table (and vocabularies) between both the query and candidate items.

A dataset for this tasks would probably be feeding your model with dictionaries somewhat like this:

```python
{"query_id": [10, 1234, 23470],
 "candidate_id": [12380, 871029, 7141]
```

**Comment by max-grzanna** [comment]
Thanks, @maciejkula, for answering my question. That really helps! 
I think I am going with a shared table. If I want to use context features like the item's manufacturer or color, should I add them to the query or candidate tower for item-to-item recommendation? Or maybe to both?

**Comment by maciejkula** [comment]
Both seems like a good starting point!

**Comment by luisceledon** [comment]
Hi @max-grzanna , did you find any code example for this? thanks in advance

**Comment by max-grzanna** [comment]
No I haven’t :/ Sorry.

**Comment by piyushdewangan54** [comment]
Hi @max-grzanna, have got any code ??
