### ISSUE TITLE
[QUESTION ] Google cloud vertex AI

### ISSUE THREAD

**Issue by ydennisy** [tensorflow/recommenders#386]
Hi @maciejkula 

I came across a new product on GCP, link is [here](https://cloud.google.com/vertex-ai/docs/matching-engine/train-embeddings-two-tower). This looks like a hosted TFRS product, I was wondering if this was built using TFRS?

**Comment by patrickorlando** [comment]
Hey @ydennisy,
tfrs uses in-batch negative sampling. This means for each positive example, we use all other items in the batch as negatives.

Here's an example explanation https://github.com/tensorflow/recommenders/issues/334#issuecomment-918873740

**Comment by ydennisy** [comment]
Ahhh yes sorry thanks @patrickorlando !!
