### ISSUE TITLE
[Question] How to replace the user_id embedding with representation of an user cart (on e-shop)?

### ISSUE THREAD

**Issue by almirb** [tensorflow/recommenders#408]
Hi!
In a scenario where we have a list of product purchases on an e-shop, we want to predict what could be the complementary itens the user may buy together (aka _customers who bought this item also bought..._).

I think the user_id embedding on the query model may be replaced by the complementary itens of the cart when the user make a purchase.  

The reason of replacing the user_id is to detach the recommendations from a specific id and giving similar recommendations for users with the same itens on cart instead (new users will also benefit on that). 

How to represent this complementary itens on an embedding? Or I'm conceptually wrong and there is a better way?
Thanks!

**Comment by patrickorlando** [comment]
Hey @almirb,

One possible way is to take your records of orders and for each item in the cart, subtract it from the set of items. The remaining items can be joined into a delimited string and passed to your query tower.

| cart_items | target_item |
|:-----------|:------------|
| "b,c,d"       | "a"               | 
| "a,c,d"       | "b"               | 
| "a,b,d"       | "c"               | 


Your query tower should split the string with `tf.strings.split`, passed them to your `StringLookup` and `Embedding` Layers, and then apply `GlobalAveragePooling` before passing the result to your MLP.
You may also be able to use the `TextVectorization` layer in place of the first two layers above.

I would suggest using the same embedding layer to encode items for both your query and candidate towers.

Take this with a grain of salt, I don't know your problem in detail or whether this will work well, but it's a simple starting point.

Good luck!

**Comment by kmcmearty** [comment]
Check out this paper: https://arxiv.org/abs/1910.12757
# A Large-Scale Deep Architecture for Personalized Grocery Basket Recommendations

Walmart describes item-user complementary items for in basket grocery recommendations.

Theyre using their own variant of the triple2vec model. 

I found this library which implements a triple2vec model where you might be able to examine the logic there to understand how they implement complementary items. 
https://github.com/beta-team/beta-recsys

**Comment by maciejkula** [comment]
Patrick's answer here is on point. The common pattern for these kinds of approaches is to:

1. Take your basket with N items.
2. For each item in your basket, construct a training example that treats the current item as the target, and the other items as features of the query tower.
3. Train as usual.

**Comment by almirb** [comment]
> Patrick's answer here is on point. The common pattern for these kinds of approaches is to:
> 
> 1. Take your basket with N items.
> 2. For each item in your basket, construct a training example that treats the current item as the target, and the other items as features of the query tower.
> 3. Train as usual.

I'm making progress going forward with @patrickorlando answer. :)

**Comment by OmarMAmin** [comment]
Hi @almirb 

Any insights about how this went so far? :)

**Comment by almirb** [comment]
> Hi @almirb
> 
> Any insights about how this went so far? :)

Hi @OmarMAmin !
After struggling a while with Tensorflow Recommenders, we decided to start simpler and switched to LightFM...  It worked ok for us.
