### ISSUE TITLE
[Question] How to remove accents on characters when using custom tokenization?

### ISSUE THREAD

**Issue by almirb** [tensorflow/recommenders#410]
Hello!

I usually load data from pandas (using `tf.data.Dataset.from_tensor_slices`) I got a lot of accented text (portuguese language).
Ex.: 
"Pão de queijo"  =>  tf.Tensor(b'P\xc3\xa3o de queijo', shape=(), dtype=string)

I'm planning to use tokenization in some columns, then I added some code to remove stopwords and other adjustments (custom standarization).  
One thing I couldn't do, was removing accents from words...  usually that's done using `<my string>.decode('utf-8')`, but that isn't allowed on tensors at model fit time.  

```
def custom_standardization(input_data): 
    decoded = input_data.decode('utf-8') #     <--- that doesn't work :(
    lowercase = tf.strings.lower(decoded)    
    stripped_html = tf.strings.regex_replace(lowercase, r'\b\w{1,2}\b', ' ' )
    stripped_html = tf.strings.regex_replace(stripped_html, r'\S*\d+\S*', ' ' )
    stripped_html = tf.strings.regex_replace(stripped_html, r'@([A-Za-z0-9_]+)', ' ' )
    for i in stopwords_br:
        stripped_html = tf.strings.regex_replace(stripped_html, f' {i} ', ' ')
    return tf.strings.regex_replace(
        stripped_html, "[%s]" % re.escape(string.punctuation), ''    
    )

AttributeError: 'Tensor' object has no attribute 'decode'
```

How can I remove the accents from the words avoiding the "\xc3\xa3o" strings?
Thanks!

**Comment by patrickorlando** [comment]
Unicode string normalisation might work here,
```python
import unicodedata
text = 'Pão de queijo'
unicodedata.normalize('NFKD', text).encode('ascii', 'ignore')
# b'Pao de queijo'
```

**Comment by almirb** [comment]
I tried it. But doesn't work.  I need to do this process but in dealing with tensors intead of strings. 

```
TypeError: in user code:
.......
        inputs = self._standardize(inputs)
    File "/tmp/ipykernel_6771/4142131942.py", line 13, in custom_standardization
        nfkd_form = unicodedata.normalize('NFKD', input_data)

    TypeError: normalize() argument 2 must be str, not Tensor
```

**Comment by patrickorlando** [comment]
ah yes, I forgot that you need to make this part of your model.
Maybe you can look into the unicode normalisation in [tensorflow_text](https://www.tensorflow.org/text/api_docs/python/text/normalize_utf8).

**Comment by almirb** [comment]
> ah yes, I forgot that you need to make this part of your model. Maybe you can look into the unicode normalisation in [tensorflow_text](https://www.tensorflow.org/text/api_docs/python/text/normalize_utf8).

I tried tensorflow_text too but I didn't find something useful and ended up doing this as a pre-processing phase...  (then It got easy).
Thanks @patrickorlando for the help!
