### ISSUE TITLE
[ Question] Should we start use Functional API

### ISSUE THREAD

**Issue by xiaoyaoyang** [tensorflow/recommenders#412]
I got a lot warning like this when implementing model:
```
WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'dict'> input
```

I would like to clarify if the `functional API` is preferred when inputting multiple features into Query and Candidates tower, or is there a best practice that we could follow.

Thanks

**Comment by almirb** [comment]
As said by @maciejkula  in issue @ #188 :

> 1 can be safely ignored: in general, Keras encourages its users to use functional models for multi-input layers, but there is nothing wrong with doing so.

**Comment by xiaoyaoyang** [comment]
thanks, @almirb  I think we can close this issue!
