### ISSUE TITLE
Can we create an example for a User-User recommender?

### ISSUE THREAD

**Issue by kunal-bhadra** [tensorflow/recommenders#418]
Title. I have found only user-item recommendation examples present here. I was wondering if we could make a tutorial for recommending user profiles to other users, sort of like how Tinder or Bumble functions. Would that please be possible, or at least if not that, point to possible resources present?

**Comment by muhajirakbarhsb** [comment]
you can replace two towers with parameter user for candidate and query tower

**Comment by kunal-bhadra** [comment]
Oh alright. Is there any docs I can refer to for its implementation though? that'll be really helpful. I have been struggling with this for quite some time.

**Comment by maciejkula** [comment]
@muhajirakbarhsb has got it right, thank you!
