### ISSUE TITLE
Issue with index creation when using contextual features in retrieval model

### ISSUE THREAD

**Issue by swattstgtg** [tensorflow/recommenders#435]
I've been following the tutorial at https://www.tensorflow.org/recommenders/examples/context_features to try to add contextual features to my Retrieval model. 

When creating the index using `BruteForce.index_from_dataset`, there is an error in `_check_candidates_with_identifiers` when the input dataset is a dictionary, eg.

```
> print(self.item_dataset.element_spec)
{'x1': TensorSpec(shape=(), dtype=tf.string, name=None), 'x2': TensorSpec(shape=(), dtype=tf.string, name=None)}
```

Code called:

```
index.index_from_dataset(
    tf.data.Dataset.zip(
        (
            self.item_dataset.batch(100),
            self.item_dataset.batch(100).map(self.item_model),
        )
    )
)
```

Error:

```
File "/opt/ml/code/src/model.py", line 111, in create_prediction_index
    index.index_from_dataset(
  File "/usr/local/lib/python3.8/site-packages/tensorflow_recommenders/layers/factorized_top_k.py", line 198, in index_from_dataset
    _check_candidates_with_identifiers(candidates)
  File "/usr/local/lib/python3.8/site-packages/tensorflow_recommenders/layers/factorized_top_k.py", line 128, in _check_candidates_with_identifiers
    if candidates_spec.shape[0] != identifiers_spec.shape[0]:
AttributeError: 'dict' object has no attribute 'shape'
```

I would guess that `_check_candidates_with_identifiers` needs to check the shapes of each element in the dict?

**Comment by swattstgtg** [comment]
Please ignore, it appears I can't read...

If anyone in the future has this issue, `BruteForce.index_from_dataset` requires a "Dataset of candidate embeddings or (candidate identifier, candidate embedding) pairs"

Something like this will work if you have contextual features for your candidates

```
index.index_from_dataset(
    tf.data.Dataset.zip(
        (
            self.item_dataset.batch(100).map(lambda x: x["item_id"]),
            self.item_dataset.batch(100).map(self.item_model),
        )
    )
)
```

**Comment by WiFeng** [comment]
I encounter it too.. How does solve it ?
