### ISSUE TITLE
[Question] How to properly add numeric values to the model?

### ISSUE THREAD

**Issue by xiaoyaoyang** [tensorflow/recommenders#446]
Under this link: https://www.tensorflow.org/recommenders/examples/context_features, the timestamp got "adapt", which it seems to adjust the mean, var based on data..?
`self.normalized_timestamp.adapt(timestamps)`

Under this link though: https://www.tensorflow.org/recommenders/examples/featurization#putting_it_all_together
in the "Pull it all together", there is no `adapt` after `normalized_timestamp` was initialized...

**Comment by patrickorlando** [comment]
Hey @xiaoyaoyang,

They do the normalisation directly after instantiating the UserModel in the next code block after the text "Let's try it out:"

**Comment by maciejkula** [comment]
Closing as resolved. Thanks, Patrick!
