### ISSUE TITLE
Is it possible to get recommendations based on geolocation?

### ISSUE THREAD

**Issue by hugoferrero** [tensorflow/recommenders#450]
Let me be more explicit...

Suppose i have to recommends stores...if i put geolocations of stores as item features, would be possible to get recommendations by similarity and also by geolocation?..
does the framework accepts queries based on two features: user id and geolocation of that user?..could scann do that?

Thanks in advance.

**Comment by Cafelatte1** [comment]
I think that building the each models by geolocation is the best if you can manage them... continuously.
After fitting, predicting the stores with the models by users' geolocation information.

Or you can use geolocation feature when fitting as you said. (refer to [https://goo.gle/3kZJmSc](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa2xRbWtNYjBJNWhVbzlZb1BfUDh5YWNDMzlzQXxBQ3Jtc0tuUS02Uk1nVEg3VjVOMWhLbl9xenRqTThzZHF4Y21XemVLVEY1UTBJeF9obi12Z0FCVmdMeU5LQUtpbzdybzRKRjQ1aU90RjZvOWhWcmkzV0wwX2F1bUFQNkNTbzU1OG1pbHhVZTJWSHVRR284ay04aw&q=https%3A%2F%2Fgoo.gle%2F3kZJmSc))

**Comment by hugoferrero** [comment]
Thanks for answering @Cafelatte1 

..what do you mean  whan you say "building the each models by geolocation"?
