### ISSUE TITLE
I need help optimizing for either many CPU cores or # GPUs > 1

### ISSUE THREAD

**Issue by mark-watson** [tensorflow/recommenders#456]
I train using 4 Tesla 100s, one is busy about 1/10 of the time, and the others are very rarely utilized.

I have also tried 72 vCPU EC2 instances (c5.18xlarge) with MKL-DNN support in TensorFlow and during training only 1 vCPU is running hot, the other 71 vCPU are idling.

I have searched for solutions and nothing I have tried improves training efficiency.

I would very much appreciate references to TF Rec optimizing/benchmarking advice.

**Comment by mustfkeskin** [comment]
What is your batch_size and embedding size
