### ISSUE TITLE
How to change the architecture of query model with Sequential Retrieval model with Tensorflow Recommenders?

### ISSUE THREAD

**Issue by locdinh209** [tensorflow/recommenders#458]
Hi Tensorflow team,

I had already run the example of sequential retrieval with GRU (based on GRU4REC paper) but got stuck when trying to add more GRU layers in Query model architecture. Could you give me some advice to extend it?

**Comment by mustfkeskin** [comment]
Hi @locdinh209 
Query model based on  sequential model
You can add any layer and costumize your architecture

In this [tutorial](https://www.tensorflow.org/recommenders/examples/deep_recommenders) you can find example of multiple layer example

**Comment by locdinh209** [comment]
Thanks @mustfkeskin for your answer, I tried to run the example but did'nt do the same with sequential retrieval (GRU4REC).

I followed this [tutorial](https://www.tensorflow.org/recommenders/examples/sequential_retrieval), could you please give me an example?

**Comment by maciejkula** [comment]
This is a highly open-ended question - I'd suggest experimenting with increasingly more complex architectures to build familiarity with how to construct TensorFlow models.
