### ISSUE TITLE
Any tutorial without using tfds.load('movielens/100k-ratings', split="train")?

### ISSUE THREAD

**Issue by petrov826** [tensorflow/recommenders#460]
Hello dev team and community members!

This week I completed [official tutorials](https://www.tensorflow.org/recommenders/examples/quickstart) and trying to apply to my own task. 

It would be so great to have a tutorial that doesn't use tfds.load('movielens/100k-ratings', split="train").
This util function helps keep tutorials short and simple, but it seems to be some sort of black box.🤔
(Maybe that's because of my two years blank on TensorFlow)

I'd appreciate if you add a tutorial that create dataset object from csv or dataframe.
This will make it easier for anyone to put TensorFlow Recommenders to their work or Kaggle competition.
And more and more people will use this library!

This is my first issue in TensorFlow Recommenders git repo, you may feel this is not an issue...
If so I'll say sorry🙇‍♂️🙇‍♀️

**Comment by mustfkeskin** [comment]
You can train your model from dataframe like this

```
ds_target = tf.data.Dataset.from_tensor_slices(dict(df))
ds_tf = ds_target.map(lambda x: {
                                   'sku': x['sku'],
                                   'userid': x['userid'] })

model.fit(ds_tf.batch(batch_size)
```

**Comment by petrov826** [comment]
Thank you @mustfkeskin
I understood how to create dataset object from dataframe😊
I’ll post a notebook that contains below within a couple of days!
1. load dataset from dataframe of MovieLens
2. define a model
3. train a model
4. make a prediction

**Comment by petrov826** [comment]
I made a notebook(https://github.com/petrov826/tfrs/blob/main/create_dataset_in_tfrs.ipynb) on Google Colab.  
Seems to be working fine for me!!  

Now I can use tfrs in Kaggle and my own task🤗

**Comment by petrov826** [comment]
Can someone review my notebook please?
If this's fine, I'll close this issue!

**Comment by patrickorlando** [comment]
Looks good to me @petrov826.
Two comments:
1. You can use `df.to_dict('list')` to convert the dataframe into a dictionary of `(column_name, list_of_values)`, which will save you listing them all out.
2. There is a limit to the size of data you can input into `tf.data.Dataset.from_tensor_slices`, for some datasets, you may need to look into [tf.data.experimental.make_csv_dataset](https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset)
