### ISSUE TITLE
Collaborative Filtering or Content-based ?

### ISSUE THREAD

**Issue by bdikici** [tensorflow/recommenders#461]
Hey everyone,

Hope everyone is well. I am new to the recommendation system topic and was just reading through the tutorials in the tensorflow page and while reading the retrieval tutorial I was wondering whether that would be a collaborative or content-based recommendation system ?

Best regards,
bd

**Comment by AzizIlyosov** [comment]
I guess  this  type  of  recommendation is  called  hybrid  recommendation system, because in this model,   you can take  advantage  of  both, content  and  history information of  users/items

**Comment by maciejkula** [comment]
That's correct - whether your resulting model is purely collaborative depends on the inputs you feed into it.
