### ISSUE TITLE
Unable to do batch prediction on loaded DCN model. 

### ISSUE THREAD

**Issue by meg261995** [tensorflow/recommenders#477]
Hi,

I am training a DCN model for ranking purpose. The train data contains batches cached TensorFlow dataset. I achieve this with the below code. 
```
cached_train = train.shuffle(100_000).batch(8192).cache() 
cached_test = test.batch(4096).cache() 
```
where train and test are TensorFlow datasets. 

Model training and evaluation happens successfully with the below code.
```
model.fit(cached_train, epochs=epochs)
model.evaluate(cached_test, return_dict=True)
```

My requirement is to perform prediction in batches just like how the training and evaluation happens. I can do this in the session where the model is trained. i.e.,
```
model.predict(cached_test)
```
works successfully where the model is trained. But the same thing throws the below error if I try to do it in an other session.

Another session:
```
data_to_predict = mydata.batch(4096).cache()
loaded = tf.saved_model.load(model_path)
loaded(data_to_predict)
```
Throws the below error:
```
ValueError: Could not find matching concrete function to call loaded from the SavedModel.
```
I want the prediction to be done batch wise like this rather than one by one which takes a lot of time.  Any help would be appreciated. Thankyou

**Comment by patrickorlando** [comment]
Hey @meg261995 
You can't pass the dataset directly to the model because it expects a tensor input.
You need to interate over your batch.

```python
pred_batches = []
for batch in data_to_predict:
    pred_batches.append(loaded_model(batch))
```

**Comment by maciejkula** [comment]
This is the right answer - thank you, Patrick!
