### ISSUE TITLE
Error import tensorflow_recommender

### ISSUE THREAD

**Issue by claraMarti** [tensorflow/recommenders#482]
I'm trying to import tensflow_recommender and It is being impossible. The error is the next one:
`import tensorflow_recommenders as tfrs
ImportError: SystemError: <built-in method __contains__ of dict object at 0x7f379adcdc80> returned a result with an error set`
Or this other error:
`module 'tensorflow._api.v2.data' has no attribute 'AUTOTUNE'`

**Comment by mustfkeskin** [comment]
Can you install tensorflow via anaconda? 
It looks like an installation error
