### ISSUE TITLE
Is it expected to get duplicate recommendations when using ScaNN for retrieval?

### ISSUE THREAD

**Issue by cjbayron** [tensorflow/recommenders#500]
I'm getting a substantial amount of duplicates when retrieving recommendations using ScaNN vs. BruteForce.

For context, I'm testing getting 10 item recommendations for 117 users. When using BruteForce, there is completely no duplicate (out of 1170 items). But using ScaNN, I'm getting 468 duplicates in total (238 items each recommended twice) out of 1170. Is this expected?

**Comment by patrickorlando** [comment]
Hi @cjbayron,
As far as I know this shouldn't be expected. The example below doesn't reproduce your issue.
Can you reproduce the issue with a minimal example like the one below?

```python
import tensorflow as tf
import tensorflow_recommenders as tfrs

num_candidates = 1200
num_queries = 100
query_dim = 64
num_to_retrieve = 10

candidate_vecs = tf.random.normal((num_candidates, query_dim))
candidate_ids = tf.range(num_candidates)
query_vecs = tf.random.normal((num_queries, query_dim))

scann_index = tfrs.layers.factorized_top_k.ScaNN(k=num_to_retrieve)
scann_index.index(candidate_vecs, candidate_ids)

scores, ids = scann_index(query_vecs)

# Check all the returned ids are unique for each query.
all([len(set(row)) == num_to_retrieve for row in ids.numpy()])

```

**Comment by cjbayron** [comment]
thanks for the minimal example. turns out I had duplicates in my candidate IDs. closing this issue
