### ISSUE TITLE
Retrieval using only one feature of User

### ISSUE THREAD

**Issue by dexter1729** [tensorflow/recommenders#505]
I want to build deep recommender system to predict movie for a given user. I have dataset which contain information about user like its id, gender, city etc (dataset contain different rows for same user with different location city) and movie information like its title, genre etc. I can train the model using this dataset by having user information in query tower and movie information in candidate tower. But during retrieval, I only have information about user's id(this user id is also in the dataset). How to give only user id embedding in BruteForce layer for predicting movie? Like in deep recommender model, we would write  `brute_force = tfrs.layers.factorized_top_k.BruteForce(model.query_model.embedding_model.user_embedding)` but how to take this user's past locations and its gender into context while retrieving as we are can't pass whole query model?

**Comment by patrickorlando** [comment]
If these features change. You will need to have them available at inference time (research the concept of a feature store). In practice, building a production recommendation system requires more components than just the model. 

If the query features about the users do not change, then you can hack your way around this by calculating the full vector for each user in your training set (after training). You can then create a new embedding layer and query model with these vectors and then at inference you'll only perform a lookup on the `user_id`. There are no examples of this.

**Comment by dexter1729** [comment]
@patrickorlando how would we be creating full vector for user and how to create new query model? can you give small code example in the context of  user-movie as explained in tutorials?

**Comment by patrickorlando** [comment]
Here's the general idea, I haven't tested this so you may encounter some errors.
```python
# users_ds is tf.data.Dataset with each record containing a user_id and the other features.
user_id_batches = []
user_vec_batches = []
for batch in user_ds:
    user_vec_batches.append(model.query_model(batch)) 

serving_user_vecs = tf.concat(user_vec_batches, axis=0)

num_users, vector_dim = tf.shape(serving_user_vecs)

serving_user_embedding_layer = tf.keras.layers.Embedding(num_users, vector_dim, mask_zero=False)

serving_user_embedding_layer.set_weights([serving_user_vecs])

serving_user_lookup = tf.keras.layers.experimental.preprocessing.StringLookup(
    vocabulary=tf.concat(user_id_batches, axis=0), mask_token=None, num_oov_indices=0
)

brute_force = tfrs.layers.factorized_top_k.BruteForce(tf.keras.Model([
    serving_user_lookup,
    serving_user_embedding_layer
])
```

**Comment by dexter1729** [comment]
@patrickorlando I have some doubts:

1) is the `model` in this code already trained by original dataset?  Original dataset contain multiple rows of same user with different features (of user).

2) in `user_ds` dataset, can we just aggregate all particular features for a particular user? Like for user_id = 1, his locations column in different rows are x, y, z. So we can create [x,y,z] in user_ds dataset

**Comment by patrickorlando** [comment]
@dexter1729 as I mentioned, you can only do this if the additional features for each user *do not* change. If you have features like the users location, you cannot do this. Your question doesn't make much sense if this is the case. 

Your only option is to serve these features to the model at inference time.

**Comment by patrickorlando** [comment]
@dexter1729 
1. Yes, it's the trained model. You are calculating the query vector based on a different dataset, containing only one row per user.

2. You would need to modify your query model to accept an array of user locations and take the average vector or alternatively take the most recent location. This hack is not such a great idea when the additional features change, since you will not be capturing the true user location at inference time and are therefore introducing training-serving skew. You can still give this a try depending on your use-case and requirements, but the correct way to handle this is to serve these features to the model at inference time.
