### ISSUE TITLE
excluding already seen items from retrieval model 

### ISSUE THREAD

**Issue by Abdelrahman-7gab** [tensorflow/recommenders#523]
I was following the Movielens basic retrieval model tutorial:
https://www.tensorflow.org/recommenders/examples/basic_retrieval
and In our use case it's crucial that the user doesn't get recommended the same items that he interacted with before. 
I did find this query_with_exclusions function: 
https://www.tensorflow.org/recommenders/api_docs/python/tfrs/layers/factorized_top_k/TopK#query_with_exclusions
but I still don't know how to apply it to our use case and how to exclude certain items for certain users...
if someone can help me with an example that would be great.

**Comment by maciejkula** [comment]
This is a common need, and is normally handled in a business logic layer that lives on top of the results returned by your model.
