### ISSUE TITLE
Can multiple query models be provided when building a retrieval index?

### ISSUE THREAD

**Issue by phenilb** [tensorflow/recommenders#541]
Consider the following:

I have a TFRS model for a retail e-commerce use-case that has a query model and a candidate model. The query model leverages multiple context features like the `age` of a user or the `gender` of a user just like how timestamp has been utilized in [this](https://www.tensorflow.org/recommenders/examples/context_features) doc example.

`model = RetailModel()`

I am building a `ScaNN retrieval index` that uses the query model of the TFRS model as its own query model like so:

```
scann = tfrs.layers.factorized_top_k.ScaNN(query_model=model.query_model, k=5)

```

Now, the query model of our TFRS model makes use of not only user (`user_id`) embeddings, but also other feature embeddings including `age` embedding and `timestamp` embedding. It concatenates all these feature embeddings and then feeds them to a dense layer that outputs a final embedding of size 32. 

When performing inference using the `scann` index created like above, the expected input for the inference requires that I input a dict that includes all the features including `user_id`, `age`, `gender` and `timestamp` in order to retrieve recommendations.

But when serving/deploying such a model(scann index), all the user information along with all features is not available all the time when performing inference.

In such a case, I created a new `ScaNN` index as follows:

```
scann = tfrs.layers.factorized_top_k.ScaNN(query_model=model.query_model.user_embedding, k=5)

```
where, user_embedding is only a part of the query_model, not the whole query model.
Now, if I don't have other information about a user except for their id, I can simply pass the `user_id` as input to the `scann` index and retrieve recommendations.

Now my question is this:
Do I have to create multiple `ScaNN` indexes in order to handle multiple types of input for retrieval? This could lead to combinatorial explosion for combinations of input features. Is this the right way to go? Is there a way to provide multiple `query_model`(s) to `ScaNN` when creating the index? Like through a list of query models or something that allows me to handle multiple types of inputs.

The `ScaNN` layer documentation goes as such:
```
tfrs.layers.factorized_top_k.ScaNN(
    query_model: Optional[tf.keras.Model] = None,
    k: int = 10,
    distance_measure: Text = 'dot_product',
    num_leaves: int = 100,
    num_leaves_to_search: int = 10,
    training_iterations: int = 12,
    dimensions_per_block: int = 2,
    num_reordering_candidates: Optional[int] = None,
    parallelize_batch_searches: bool = True,
    name: Optional[Text] = None
)
```
Some sample inputs that I would like a single `ScaNN` index to handle:

```
input_1 = {'user_id': np.array(['0001fd6190edaaf884bcaf3d49edf079'])}

input_2 = {'user_id': np.array(['0001fd6190edaaf884bcaf3d49edf079']), 'age':np.array(['42'])}

input_3 = {'age': np.array(['42']), 'timestamp':np.array(['1661530698'])}
```

I want a single `ScaNN` index to be able to recommend candidates for all of the above inputs. Is that possible?

**Comment by patrickorlando** [comment]
Hey @phenilb,
For features that change very infrequently with respect to your training cadence, you could materialise these features into a single embedding for the user which you use for serving.
This can only work for certain features that map 1:1 with your user, and you have to tolerate a level of error introduced if these features change.

See this #505 for further info
