### ISSUE TITLE
Example of sequential retrieval inference

### ISSUE THREAD

**Issue by petar-savov** [tensorflow/recommenders#545]
I'm following the sequential retrieval tutorial - https://www.tensorflow.org/recommenders/examples/sequential_retrieval which ends at the evaluation stage and it doesn't show how to make predictions. If I have a trained model like the one at the end of the tutorial, how can I use it to make predictions for a new sequence of items?

The goal is to pass a sequence of items like

> {'context_movie_id': array([b'2589', b'202', b'1038', b'1767', b'951', b'129', b'1256', b'955',
       b'3097', b'3462']}

to the model and get a prediction for the next item(s).

**Comment by maciejkula** [comment]
The process is the same as for any retrieval model, and described [here](https://www.tensorflow.org/recommenders/examples/basic_retrieval#making_predictions).
