### ISSUE TITLE
Indexing using ScaNN without loading all data into memory

### ISSUE THREAD

**Issue by violetdang1** [tensorflow/recommenders#587]
Hi, I'm working with a very large dataset, and I was wondering if it's possible to index using ScaNN without loading all data into memory? How would I do this? 

Thanks

**Comment by maciejkula** [comment]
The ScaNN interface accepts a fully-materialized 2D tensor of embeddings for indexing - I think this will be the lower bound on the amount of memory you'll need.

**Comment by violetdang1** [comment]
Hi @maciejkula, thanks for the quick response. By `fully-materialized 2D tensor of embeddings`, do you mean ScaNN take 2D tensor directly for indexing - so I won't need much memory because I won't be passing raw/big dataset? 

Another question I have is ScaNN model size get quite big with a large number of vectors. Is there a work around for the model size, we have 100M+ vectors. Thanks again!

**Comment by patrickorlando** [comment]
To put what @maciejkula another way, ScaNN cannot index the vectors incrementally, so you at least need to fit a tensor of `num_items, embed_dim` in memory. You will need to compute the vectors, from your full dataset, but this is often done in batches using your `tf.data.Dataset`, which means you don't need to load the whole dataset in memory.

To ensure you aren't storing the entire set of embeddings into the scaNN model, ensure this parameter is set to `false`.
Other than that, num_leaves might have some effects, but I'm not sure how much.
https://github.com/tensorflow/recommenders/blob/2ac1483671dc33c0ff1800a4a5f70f7dd20c7471/tensorflow_recommenders/layers/factorized_top_k.py#L641-L645
