### ISSUE TITLE
Saving for reuse - rebuild bruteforce with new items

### ISSUE THREAD

**Issue by EdwardALockhart** [tensorflow/recommenders#589]
I have a use case where I would want to recreate tfrs.layers.factorized_top_k.BruteForce() to take into account new items for consideration (even if they had not been trained on directly).

Therefore saving the brute force layer doesn't fit this use case as k and the items for consideration are baked in (you'd need your retrieval model to get the embeddings of any new items that you'd want to supply as candidates when recreating it). So I also need to save my retrieval model to process the new items when rebuilding the brute force layer. However this throws up an error as documented elsewhere (https://gitcodeask.cc/issue/unable-to-save-multi-task-recommender-model-recommenders.html).

Is this a sensible approach? It doesn't seem to be covered anywhere as a use case.

```
# Save the retrieval model for later, then load it in to replicate reusing it in the future
retrieval_path = os.path.join(directory, "retrieval")
retrieval_model.task = tfrs.tasks.Retrieval() # handle the previously mentioned error
tf.saved_model.save(retrieval_model, retrieval_path)
retrieval_model = tf.saved_model.load(retrieval_path)

# New items that we want to consider
items = tf.data.Dataset.from_tensor_slices(new_data[["item", "item_type", "item_description"]].drop_duplicates(subset = "item").to_dict(orient = "list"))

# Rebuild the brute force layer
recommender = tfrs.layers.factorized_top_k.BruteForce(retrieval_model.query_model, k = 50)
recommender.index_from_dataset(items.batch(128).map(lambda x: (x["item"], retrieval_model.candidate_model(x))))

# Make recommendations
```

**Comment by patrickorlando** [comment]
You can save the query and candidate model separately. That will resolve your serialisation issue.
