### ISSUE TITLE
Recommending movies from different genres

### ISSUE THREAD

**Issue by violetdang1** [tensorflow/recommenders#590]
Hi, going off from the tutorial example, what's the best way to to recommend movies by Genres? Let's say each movie has a Genre field, and now for user X, I want to get top 10 Horror movies. Does ScaNN support this type of recommendations or I'd have to build indexes for multiple genres? If I have 1M genres, would it still be advisable?

Thanks

**Comment by EdwardALockhart** [comment]
I think all you can do is generate your recommendations and the filter them afterwards for the genre of your choice.

**Comment by violetdang1** [comment]
but then the number of candidates I have to generate would be very large, I have 100M candidates

**Comment by EdwardALockhart** [comment]
I think you must be confused. The whole process is to get a pool of items and narrow them down to a subset in the retrieval stage. You take what can be millions of items to maybe a few tens of items. So you would filter this generated list for your genres.
