### ISSUE TITLE
Store and retrieve item description embeddings

### ISSUE THREAD

**Issue by hkristof03** [tensorflow/recommenders#615]
I fine-tuned a pre-trained BERT model from TF Hub by feeding the item descriptions and doing multi-label classification. Then, I generated the vector representations of the item descriptions which I saved to a numpy file, which contains <item_id>, <vector> pairs.

Because the vectors are of shape (768) it is not feasible to store them with the train data for neither the Retrieval or the Ranking models. What I would like to do is to store these pairs in a TF data structure which I can access and query during the training. So I want to retrieve the item description vectors corresponding to given item ids in the given batch.

I found [tf.lookup.StaticHashTable](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable) but I struggle to create the table with vector values. I tried many different options for the default value, but I always get errors like this:

`
ValueError: Shapes (3, 2) and () must have the same rank
`

The toy example that produces the above error:

```
keys_tensor = tf.constant(['a', 'b', 'c'])
vals_tensor = tf.constant([[0,0], [1,1], [3,3]])
default_value = tf.constant([-1, -1])

init = tf.lookup.KeyValueTensorInitializer(
    keys=keys_tensor,
    values=vals_tensor,
)

table = tf.lookup.StaticHashTable(
    initializer=init,
    #default_value=tf.expand_dims(default_value, axis=0),
    default_value=vals_tensor,
    name="whatever"
)
```

I would greatly appreciate a working example or another suggestion how to solve this. The standard python data structures do not work during the training when I want to access them.

@maciejkula , @patrickorlando ?

**Comment by maciejkula** [comment]
By far the easier solution is to write these embeddings out into your training data. Why is this not feasible?

**Comment by hkristof03** [comment]
Because I have like 100M rows of data, around 30k items, vectors of length 768 and type float32, it would require a ton of memory with mostly duplications.

**Comment by patrickorlando** [comment]
hey @hkristof03,
You could treat these as a non-trainable embedding layer.
I've used a standard `tf.keras.layers.Embedding(..., trainable=False)` embedding. You can create a `tf.keras.layers.StringLookup`, or re-use the same lookupIf it fits on your GPU then your embeddings can sit there, if it doesn't you can place them on the CPU and do the lookups in the `tf.data` pipeline.

**Comment by hkristof03** [comment]
@patrickorlando thanks for your solution!

As a working toy example:

```
vocab = list('abcdefghij')

weights = np.array([[float(i)] * 5 for i in range(1, 11)]).astype(np.float32)
# add a default vector for the unknown item ids
weights = np.concatenate((np.zeros((1, weights.shape[1])), weights), axis=0)

sl = tf.keras.layers.StringLookup(vocabulary=vocab)
el = tf.keras.layers.Embedding(weights.shape[0], weights.shape[1], weights=[weights], trainable=False)

item_description_embedding = tf.keras.Sequential([sl, el])

print(item_description_embedding(tf.constant(['unknown', 'a', 'c'])))
```

produces:

```
<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.]], dtype=float32)>
```
