### ISSUE TITLE
[Question] Ranking for implicit data

### ISSUE THREAD

**Issue by jillwalker99** [tensorflow/recommenders#627]
Hello all,
I've just recently started using Tensorflow and I'm planning to develop a recommender system with only implicit data (clicks). Does the ranking for implicit data work identically as in the Tensorflow example basic_ranking ? Or what changes have to be made or should be made when using implicit data e.g. changes of activation to sigmoid or similar. 
Many thanks in advance for your help.

**Comment by patrickorlando** [comment]
Hi @jillwalker99,
Often during the ranking stage explicit ratings or negatives are included in the dataset.
If you only have positive interactions, I would suggest starting with a retrieval model, which will handle the negative sampling for you.

If you then want to proceed with a ranking model, you'll have a baseline to compare to.
For a ranking model you will need to experiment with negative sampling strategies.
I'm not an expert here, but I believe that the ranking model with only sampled negatives might not offer that much of an advantage over the retrieval model, unless you have rich features and expect there to be strong interactions between these query/candidate features.
But again, take this with a grain of salt.

I'm keen to hear about your results!

**Comment by jillwalker99** [comment]
Hi @patrickorlando,

Thank you very much for your feedback. I will then try to use ratings (like or dislike) in the ranking phase.
