### ISSUE TITLE
How to use remove_accidental_hits?

### ISSUE THREAD

**Issue by mustfkeskin** [tensorflow/recommenders#631]
We need to set candidate_ids in order to use remove_accidental_hits. A sample can have more than one positive sample in the whole data set. How we can give candidate_ids. List of list or which data type suitable for this

 candidate_ids: Optional tensor containing candidate ids. When given
        enables removing accidental hits of examples used as negatives. An
        accidental hit is defined as an candidate that is used as an in-batch
        negative but has the same id with the positive candidate.

**Comment by patrickorlando** [comment]
Hey @mustfkeskin,
This comment should answer your question. https://github.com/tensorflow/recommenders/issues/334#issuecomment-894873355

**Comment by mustfkeskin** [comment]
You gave such an example, it's pretty self explanatory.

`If it helps, think of word2vec. Two different examples passed through the model could have the same context The front [door] was left open. and The front [gate] was left open.. For each example you sample negatives, but you don't prevent sampling negatives which are positives for other examples in your corpus.`


We will give this information like candidate_sampling_probabilities as far as I understand from the source code.
A user can have more than one positive sample, it seems like it might not be enough to give the samples in the batch.  I think it should look at all the data. How is tf behaving here.

The information here will be similar to the candidate, right?
How we can choose this similar items?

**Comment by mustfkeskin** [comment]
Thanks @patrickorlando
