### ISSUE TITLE
[Question] Brute Force Query with Inclusions?

### ISSUE THREAD

**Issue by ericy51** [tensorflow/recommenders#680]
I have a Brute Force retrieval model setup to serve product recommendations. I was planning to use these recommendations at the top of different category pages of products (shoes,shirts,pants,etc.) I know that _tfrs.layers.factorized_top_k.BruteForce_ has the option to exclude the products returned by using _query_with_exclusions_ but I was wondering if it's possible to do the opposite and pass a list of products that we only want to include?

I was thinking from a productionalization standpoint this would be more efficient based on my use case

**Comment by rlcauvin** [comment]
It looks like the [code](https://github.com/tensorflow/recommenders/blob/v0.7.3/tensorflow_recommenders/layers/factorized_top_k.py#L504-L593) for query_with_exclusions sets the scores for excluded items to very low values. I imagine you could extend tfrs.layers.factorized_top_k.BruteForce to have a query_with_inclusions function that uses similar logic but adds a large number to the scores of all the included items.
