### ISSUE TITLE
Zero factorizedtopk accuracy

### ISSUE THREAD

**Issue by thani-ath-nain-khurshid** [tensorflow/recommenders#700]
I am training a tensorflow recommenders model on user ids and product features like category sale percentage etc   following the tutorial at https://www.tensorflow.org/recommenders/examples/deep_recommenders but whatever I do my accuracy as computed by the retrieval task is always 0 Even though loss is decreasing. What can be the cause here?

**Comment by mustfkeskin** [comment]
Hi you need set compute_metrics = True
```
return self.task(
        query_embeddings, movie_embeddings, compute_metrics=not training)
```

But if you do this, the training time will be longer.

**Comment by thani-ath-nain-khurshid** [comment]
Thanks
