### ISSUE TITLE
Unexpected git status after cloning when using git v. 2.24.1

### ISSUE THREAD

**Issue by vreyespue** [tensorflow/recommenders#84]
Important note: this issue does not happen when using the `git v. 2.11.0` under Linux.

Dear all, I got a strange git status when cloning the repo into macOS, in which I have the `git v. 2.24.1` installed.
It looks like the `main` branch is kind of corrupted (see below). The problem arises within the folder `tools` (deleted files).
Did you see before something like that? Maybe it has to do with git hooks? Can it be easily fixed?

Disclaimer: maybe it does not have anything to do with the repo itself. If so, please excuse me (I am just trying to be helpful).

```
$ git --version
git version 2.24.1

$ git clone https://github.com/tensorflow/recommenders.git
Cloning into 'recommenders'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 810 (delta 32), reused 49 (delta 18), pack-reused 742
Receiving objects: 100% (810/810), 316.14 KiB | 969.00 KiB/s, done.
Resolving deltas: 100% (555/555), done.

$ cd recommenders

$ git status -v
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    tools/BUILD

no changes added to commit (use "git add" and/or "git commit -a")

$ git reset --hard
HEAD is now at f48e3ed Merge pull request #81 from hyphmongo:hyphmongo-patch-1

git status -v
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    tools/build/pip_install.sh
	deleted:    tools/build/release.sh
	deleted:    tools/build/test.sh
	deleted:    tools/build/utils.sh

no changes added to commit (use "git add" and/or "git commit -a")

$ git reset --hard
HEAD is now at f48e3ed Merge pull request #81 from hyphmongo:hyphmongo-patch-1

$ git status -v
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    tools/BUILD

no changes added to commit (use "git add" and/or "git commit -a")
```
Many thanks and best regards.

**Comment by maciejkula** [comment]
Thanks for the detailed message. Could you help me hone in on what is wrong with the status above?

**Comment by maciejkula** [comment]
I see, some files in your version are staged for delete.

**Comment by vreyespue** [comment]
Hi @maciejkula, many thanks for you nice reply.
The main issue is that some files are staged for delete directly after cloning the repo. And interestingly, these files are staged automatically, i.e. without any intervention from my side.
Actually this never happened to me before, and this is why I am raising this issue. Importantly, one of my coworkers could reproduce this issue in a similar setup (meaning that this is not an issue within a single machine, but might affect many users).
As already mentioned, this issue happens (at least) when using `git v. 2.24.1` on macOS.
From here some questions:

1. Can this issue be reproduced among other configurations? (i.e. other git versions and/or operating systems),
2. What is the cause for this to happen?, and
3. Is there an easy fix?

Many thanks and best regards

**Comment by maciejkula** [comment]
This is almost certainly an issue with git rather than this specific repo. Cursory Googling reveals that this is relatively common. Could you try the suggestions in [this SO](https://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-a-git-clone) thread and see if any of those help?

**Comment by vreyespue** [comment]
Dear @maciejkula, many thanks, that's totally right. As described in [this answer](https://stackoverflow.com/a/5022417/6261650), the problem is that the macOS file system is not case-sensitive (as opposed to Linux). However, there are two entries within the folder `tools` which are interpreted as having the same name (the file `BUILD` and the subfolder `build`).
```
$ git ls-tree HEAD tools/
100644 blob 19937fd785a965762edad87646b30ef4029b0aca	tools/BUILD
040000 tree 04c1065a6384658d4d09d2a1be4a029142afcc0e	tools/build
100644 blob 9ced0ca8c6b46c40d124f721271464c27bb8f7a3	tools/build_api_docs.py
```
The consequence is the following: macOS tries to get rid of one of these two (apparently duplicate) entries automatically, which explains the weird `git status` outputs described above.
My advice would be to change the name of one entry (the file `BUILD` or the subfolder `build`), so that those developers using non case-sensitive file systems do not get any problems in the future.
Anyhow, and because this is certainly not a problem of this specific repo (but rather a general one), I proceed to close the issue.
Once again, many thanks for your support and best regards 😄 👍

**Comment by maciejkula** [comment]
That's fantastic investigative work!

I'll have a think and see if I can figure out a way around this.

**Comment by vreyespue** [comment]
Although this is certainly not a problem of this specific repo (but rather a general one), I suggest to perform a small change in order to enable developers working comfortably with the repo under any file system (see PR #88).
