### ISSUE TITLE
Using bruteforce to retrieve recommendations

### ISSUE THREAD

**Issue by nishtala** [tensorflow/recommenders#87]
In this example: https://github.com/tensorflow/recommenders/blob/main/docs/examples/deep_recommenders.ipynb
Could you give an example of how to use the `tfrs.layers.ann.BruteForce` to retrieve recommendations?

**Comment by maciejkula** [comment]
Hey: it would be exactly the same as in [this tutorial](https://www.tensorflow.org/recommenders/examples/quickstart#fit_and_evaluate_it).

**Comment by nishtala** [comment]
I've tried with that. Users model expects a dictionary in deep_recommenders.ipynb.
I am not entirely sure why one would have to give timestamp to predict?

**Comment by maciejkula** [comment]
This is because in the deep recommenders tutorial we give recommendations based on both the user's identity and the current timestamp.

To retrieve recommendations you can try the following:
```
nn = tfrs.layers.ann.BruteForce(model.query_model)
nn.index(movies.batch(1024).map(model.candidate_model), identifiers=movies)

for row in ratings.batch(1).take(2):
  print(f"Best recommendations: {nn(row)[1].numpy()[:, :3].tolist()}")
```
This will yield something like:
```
Best recommendations: [[b'Some Folks Call It a Sling Blade (1993)', b'Nelly & Monsieur Arnaud (1995)', b'Patton (1970)']]
Best recommendations: [[b'Panther (1995)', b'Far From Home: The Adventures of Yellow Dog (1995)', b'Beverly Hillbillies, The (1993)']]
```
